// Fraud Detection Service - خدمة كشف الاحتيال
// Real-time fraud detection and prevention

import { PrismaClient } from '@prisma/client';
import Redis from 'ioredis';

// Type definitions (generated by Prisma after `prisma generate`)
type TargetType = 'USER' | 'ORDER' | 'TRANSACTION' | 'PAYMENT' | 'ACCOUNT' | 'LISTING' | 'REVIEW';
type AlertType = 'ACCOUNT_TAKEOVER' | 'PAYMENT_FRAUD' | 'IDENTITY_THEFT' | 'FAKE_LISTING' | 'FAKE_REVIEW' | 'MONEY_LAUNDERING' | 'PROMO_ABUSE' | 'REFUND_ABUSE' | 'VELOCITY_ABUSE' | 'BOT_ACTIVITY' | 'SUSPICIOUS_BEHAVIOR';
type Severity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
type AlertStatus = 'PENDING' | 'INVESTIGATING' | 'CONFIRMED_FRAUD' | 'FALSE_POSITIVE' | 'RESOLVED' | 'ESCALATED';
type RiskLevel = 'VERY_LOW' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
type TransactionDecision = 'APPROVED' | 'DECLINED' | 'REVIEW' | 'CHALLENGE';
type RuleType = 'VELOCITY' | 'AMOUNT' | 'LOCATION' | 'DEVICE' | 'BEHAVIOR' | 'PATTERN' | 'BLACKLIST' | 'ML_MODEL';
type BlacklistType = 'IP_ADDRESS' | 'EMAIL' | 'PHONE' | 'DEVICE_ID' | 'CARD_BIN' | 'CARD_HASH' | 'USER_ID' | 'ADDRESS';

const prisma = new PrismaClient();
const redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');

// ==========================================
// 🔍 RISK SCORING WEIGHTS
// ==========================================

const RISK_WEIGHTS = {
  velocity: 0.25,
  amount: 0.20,
  device: 0.15,
  location: 0.15,
  behavior: 0.15,
  history: 0.10,
};

const VELOCITY_THRESHOLDS = {
  hourly: { count: 5, amount: 1000 },
  daily: { count: 20, amount: 5000 },
  weekly: { count: 50, amount: 15000 },
};

// ==========================================
// 💳 TRANSACTION ANALYSIS
// ==========================================

interface TransactionData {
  transactionId: string;
  userId: string;
  amount: number;
  currency: string;
  paymentMethod: string;
  merchantId?: string;
  deviceId?: string;
  ipAddress: string;
  cardBin?: string;
  billingCountry?: string;
  shippingCountry?: string;
}

interface RiskSignal {
  type: string;
  score: number;
  description: string;
  descriptionAr: string;
}

export class FraudService {
  // ==========================================
  // 🎯 MAIN TRANSACTION ANALYSIS
  // ==========================================

  async analyzeTransaction(data: TransactionData): Promise<{
    riskScore: number;
    riskLevel: RiskLevel;
    decision: TransactionDecision;
    signals: RiskSignal[];
    requiresReview: boolean;
  }> {
    const signals: RiskSignal[] = [];
    let totalScore = 0;

    // 1. Check Blacklists
    const blacklistScore = await this.checkBlacklists(data);
    if (blacklistScore.score > 0) {
      signals.push(...blacklistScore.signals);
      totalScore += blacklistScore.score * 100; // Blacklist = instant high risk
    }

    // 2. Velocity Analysis
    const velocityScore = await this.analyzeVelocity(data);
    signals.push(...velocityScore.signals);
    totalScore += velocityScore.score * RISK_WEIGHTS.velocity * 100;

    // 3. Amount Analysis
    const amountScore = await this.analyzeAmount(data);
    signals.push(...amountScore.signals);
    totalScore += amountScore.score * RISK_WEIGHTS.amount * 100;

    // 4. Device Analysis
    const deviceScore = await this.analyzeDevice(data);
    signals.push(...deviceScore.signals);
    totalScore += deviceScore.score * RISK_WEIGHTS.device * 100;

    // 5. Location Analysis
    const locationScore = await this.analyzeLocation(data);
    signals.push(...locationScore.signals);
    totalScore += locationScore.score * RISK_WEIGHTS.location * 100;

    // 6. User History
    const historyScore = await this.analyzeUserHistory(data.userId);
    signals.push(...historyScore.signals);
    totalScore += historyScore.score * RISK_WEIGHTS.history * 100;

    // 7. Apply ML Model (if available)
    const mlScore = await this.applyMLModel(data);
    if (mlScore) {
      signals.push(...mlScore.signals);
      totalScore = (totalScore + mlScore.score * 100) / 2; // Average with ML
    }

    // Normalize score
    const riskScore = Math.min(100, Math.max(0, totalScore));
    const riskLevel = this.getRiskLevel(riskScore);
    const decision = this.makeDecision(riskScore, signals);

    // Store transaction risk
    await prisma.transactionRisk.create({
      data: {
        transactionId: data.transactionId,
        userId: data.userId,
        amount: data.amount,
        currency: data.currency,
        paymentMethod: data.paymentMethod,
        merchantId: data.merchantId,
        riskScore,
        riskLevel,
        signals: signals as any,
        decision,
        requiresReview: decision === 'REVIEW',
      },
    });

    // Create alert if high risk
    if (riskScore >= 70) {
      await this.createAlert({
        targetType: 'TRANSACTION',
        targetId: data.transactionId,
        alertType: 'PAYMENT_FRAUD',
        severity: riskScore >= 90 ? 'CRITICAL' : 'HIGH',
        riskScore,
        detectedBy: 'RealTimeAnalysis',
        confidence: riskScore / 100,
        indicators: signals,
        rawData: data,
      });
    }

    return {
      riskScore,
      riskLevel,
      decision,
      signals,
      requiresReview: decision === 'REVIEW',
    };
  }

  // ==========================================
  // 🚫 BLACKLIST CHECKS
  // ==========================================

  private async checkBlacklists(data: TransactionData): Promise<{ score: number; signals: RiskSignal[] }> {
    const signals: RiskSignal[] = [];
    let score = 0;

    const checks = [
      { type: 'IP_ADDRESS' as BlacklistType, value: data.ipAddress },
      { type: 'DEVICE_ID' as BlacklistType, value: data.deviceId },
      { type: 'USER_ID' as BlacklistType, value: data.userId },
      { type: 'CARD_BIN' as BlacklistType, value: data.cardBin },
    ].filter(c => c.value);

    for (const check of checks) {
      const blacklisted = await prisma.blacklist.findFirst({
        where: {
          entryType: check.type,
          value: check.value!,
          isActive: true,
          OR: [
            { expiresAt: null },
            { expiresAt: { gt: new Date() } },
          ],
        },
      });

      if (blacklisted) {
        score = 1; // Instant max risk
        signals.push({
          type: 'BLACKLIST',
          score: 1,
          description: `${check.type} is blacklisted: ${blacklisted.reason}`,
          descriptionAr: `${check.type} في القائمة السوداء: ${blacklisted.reasonAr || blacklisted.reason}`,
        });
      }
    }

    return { score, signals };
  }

  // ==========================================
  // ⚡ VELOCITY ANALYSIS
  // ==========================================

  private async analyzeVelocity(data: TransactionData): Promise<{ score: number; signals: RiskSignal[] }> {
    const signals: RiskSignal[] = [];
    let score = 0;

    const now = new Date();
    const hourAgo = new Date(now.getTime() - 60 * 60 * 1000);
    const dayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

    // Get velocity from Redis (faster) or DB
    const cacheKey = `velocity:${data.userId}`;
    let velocity = await redis.hgetall(cacheKey);

    if (!velocity || Object.keys(velocity).length === 0) {
      // Calculate from DB
      const [hourly, daily, weekly] = await Promise.all([
        prisma.transactionRisk.aggregate({
          where: { userId: data.userId, createdAt: { gte: hourAgo } },
          _count: true,
          _sum: { amount: true },
        }),
        prisma.transactionRisk.aggregate({
          where: { userId: data.userId, createdAt: { gte: dayAgo } },
          _count: true,
          _sum: { amount: true },
        }),
        prisma.transactionRisk.aggregate({
          where: { userId: data.userId, createdAt: { gte: weekAgo } },
          _count: true,
          _sum: { amount: true },
        }),
      ]);

      velocity = {
        hourlyCount: String(hourly._count),
        hourlyAmount: String(hourly._sum.amount || 0),
        dailyCount: String(daily._count),
        dailyAmount: String(daily._sum.amount || 0),
        weeklyCount: String(weekly._count),
        weeklyAmount: String(weekly._sum.amount || 0),
      };

      // Cache for 5 minutes
      await redis.hmset(cacheKey, velocity);
      await redis.expire(cacheKey, 300);
    }

    // Check thresholds
    const hourlyCount = parseInt(velocity.hourlyCount) + 1;
    const hourlyAmount = parseFloat(velocity.hourlyAmount) + data.amount;
    const dailyCount = parseInt(velocity.dailyCount) + 1;
    const dailyAmount = parseFloat(velocity.dailyAmount) + data.amount;

    if (hourlyCount > VELOCITY_THRESHOLDS.hourly.count) {
      score += 0.4;
      signals.push({
        type: 'VELOCITY_COUNT',
        score: 0.4,
        description: `High hourly transaction count: ${hourlyCount}`,
        descriptionAr: `عدد معاملات مرتفع بالساعة: ${hourlyCount}`,
      });
    }

    if (hourlyAmount > VELOCITY_THRESHOLDS.hourly.amount) {
      score += 0.3;
      signals.push({
        type: 'VELOCITY_AMOUNT',
        score: 0.3,
        description: `High hourly amount: $${hourlyAmount.toFixed(2)}`,
        descriptionAr: `مبلغ مرتفع بالساعة: $${hourlyAmount.toFixed(2)}`,
      });
    }

    if (dailyCount > VELOCITY_THRESHOLDS.daily.count) {
      score += 0.2;
      signals.push({
        type: 'VELOCITY_DAILY',
        score: 0.2,
        description: `High daily transaction count: ${dailyCount}`,
        descriptionAr: `عدد معاملات مرتفع باليوم: ${dailyCount}`,
      });
    }

    return { score: Math.min(1, score), signals };
  }

  // ==========================================
  // 💰 AMOUNT ANALYSIS
  // ==========================================

  private async analyzeAmount(data: TransactionData): Promise<{ score: number; signals: RiskSignal[] }> {
    const signals: RiskSignal[] = [];
    let score = 0;

    // Get user's average transaction
    const userProfile = await prisma.userRiskProfile.findUnique({
      where: { userId: data.userId },
    });

    if (userProfile && userProfile.totalOrders > 5) {
      const avgTransaction = userProfile.totalSpent / userProfile.totalOrders;
      const deviation = data.amount / avgTransaction;

      if (deviation > 5) {
        score += 0.5;
        signals.push({
          type: 'AMOUNT_DEVIATION',
          score: 0.5,
          description: `Amount ${deviation.toFixed(1)}x higher than average`,
          descriptionAr: `المبلغ أعلى ${deviation.toFixed(1)} مرة من المعدل`,
        });
      } else if (deviation > 3) {
        score += 0.3;
        signals.push({
          type: 'AMOUNT_DEVIATION',
          score: 0.3,
          description: `Amount ${deviation.toFixed(1)}x higher than average`,
          descriptionAr: `المبلغ أعلى ${deviation.toFixed(1)} مرة من المعدل`,
        });
      }
    }

    // Check for round amounts (common in fraud)
    if (data.amount >= 1000 && data.amount % 100 === 0) {
      score += 0.1;
      signals.push({
        type: 'ROUND_AMOUNT',
        score: 0.1,
        description: 'Suspiciously round amount',
        descriptionAr: 'مبلغ مستدير بشكل مريب',
      });
    }

    // High value transaction
    if (data.amount > 5000) {
      score += 0.2;
      signals.push({
        type: 'HIGH_VALUE',
        score: 0.2,
        description: `High value transaction: $${data.amount}`,
        descriptionAr: `معاملة عالية القيمة: $${data.amount}`,
      });
    }

    return { score: Math.min(1, score), signals };
  }


  // ==========================================
  // 📱 DEVICE ANALYSIS
  // ==========================================

  private async analyzeDevice(data: TransactionData): Promise<{ score: number; signals: RiskSignal[] }> {
    const signals: RiskSignal[] = [];
    let score = 0;

    if (!data.deviceId) {
      score += 0.2;
      signals.push({
        type: 'NO_DEVICE',
        score: 0.2,
        description: 'No device fingerprint available',
        descriptionAr: 'لا يوجد بصمة جهاز',
      });
      return { score, signals };
    }

    // Check if device is known for this user
    const userProfile = await prisma.userRiskProfile.findUnique({
      where: { userId: data.userId },
    });

    if (userProfile) {
      const isKnownDevice = userProfile.knownDevices.includes(data.deviceId);
      
      if (!isKnownDevice) {
        score += 0.3;
        signals.push({
          type: 'NEW_DEVICE',
          score: 0.3,
          description: 'Transaction from new device',
          descriptionAr: 'معاملة من جهاز جديد',
        });

        // Check how many users use this device
        const deviceUsers = await prisma.userRiskProfile.count({
          where: { knownDevices: { has: data.deviceId } },
        });

        if (deviceUsers > 3) {
          score += 0.4;
          signals.push({
            type: 'SHARED_DEVICE',
            score: 0.4,
            description: `Device used by ${deviceUsers} accounts`,
            descriptionAr: `الجهاز مستخدم من ${deviceUsers} حسابات`,
          });
        }
      }
    }

    return { score: Math.min(1, score), signals };
  }

  // ==========================================
  // 🌍 LOCATION ANALYSIS
  // ==========================================

  private async analyzeLocation(data: TransactionData): Promise<{ score: number; signals: RiskSignal[] }> {
    const signals: RiskSignal[] = [];
    let score = 0;

    // Get IP info from cache or external service
    const ipInfo = await this.getIPInfo(data.ipAddress);

    // Check for VPN/Proxy/Tor
    if (ipInfo.isVPN) {
      score += 0.3;
      signals.push({
        type: 'VPN_DETECTED',
        score: 0.3,
        description: 'VPN connection detected',
        descriptionAr: 'تم اكتشاف اتصال VPN',
      });
    }

    if (ipInfo.isProxy) {
      score += 0.4;
      signals.push({
        type: 'PROXY_DETECTED',
        score: 0.4,
        description: 'Proxy connection detected',
        descriptionAr: 'تم اكتشاف اتصال Proxy',
      });
    }

    if (ipInfo.isTor) {
      score += 0.5;
      signals.push({
        type: 'TOR_DETECTED',
        score: 0.5,
        description: 'Tor network detected',
        descriptionAr: 'تم اكتشاف شبكة Tor',
      });
    }

    // Check billing/shipping country mismatch
    if (data.billingCountry && data.shippingCountry && data.billingCountry !== data.shippingCountry) {
      score += 0.2;
      signals.push({
        type: 'COUNTRY_MISMATCH',
        score: 0.2,
        description: `Billing (${data.billingCountry}) and shipping (${data.shippingCountry}) country mismatch`,
        descriptionAr: `عدم تطابق بلد الفوترة (${data.billingCountry}) والشحن (${data.shippingCountry})`,
      });
    }

    // Check if IP country matches user's known locations
    const userProfile = await prisma.userRiskProfile.findUnique({
      where: { userId: data.userId },
    });

    if (userProfile && ipInfo.country) {
      const isKnownLocation = userProfile.knownLocations.includes(ipInfo.country);
      
      if (!isKnownLocation && userProfile.knownLocations.length > 0) {
        score += 0.25;
        signals.push({
          type: 'NEW_LOCATION',
          score: 0.25,
          description: `Transaction from new country: ${ipInfo.country}`,
          descriptionAr: `معاملة من بلد جديد: ${ipInfo.country}`,
        });
      }
    }

    // High-risk countries
    const highRiskCountries = ['NG', 'GH', 'PK', 'BD', 'VN', 'ID', 'PH'];
    if (ipInfo.country && highRiskCountries.includes(ipInfo.country)) {
      score += 0.2;
      signals.push({
        type: 'HIGH_RISK_COUNTRY',
        score: 0.2,
        description: `Transaction from high-risk region`,
        descriptionAr: `معاملة من منطقة عالية المخاطر`,
      });
    }

    return { score: Math.min(1, score), signals };
  }

  // ==========================================
  // 📜 USER HISTORY ANALYSIS
  // ==========================================

  private async analyzeUserHistory(userId: string): Promise<{ score: number; signals: RiskSignal[] }> {
    const signals: RiskSignal[] = [];
    let score = 0;

    const userProfile = await prisma.userRiskProfile.findUnique({
      where: { userId },
    });

    if (!userProfile) {
      // New user - moderate risk
      score += 0.2;
      signals.push({
        type: 'NEW_USER',
        score: 0.2,
        description: 'New user with no history',
        descriptionAr: 'مستخدم جديد بدون سجل',
      });
      return { score, signals };
    }

    // Check chargeback history
    if (userProfile.chargebackCount > 0) {
      const chargebackRate = userProfile.chargebackCount / Math.max(1, userProfile.totalOrders);
      if (chargebackRate > 0.1) {
        score += 0.5;
        signals.push({
          type: 'HIGH_CHARGEBACK',
          score: 0.5,
          description: `High chargeback rate: ${(chargebackRate * 100).toFixed(1)}%`,
          descriptionAr: `معدل استرداد مرتفع: ${(chargebackRate * 100).toFixed(1)}%`,
        });
      } else if (chargebackRate > 0.05) {
        score += 0.3;
        signals.push({
          type: 'MODERATE_CHARGEBACK',
          score: 0.3,
          description: `Moderate chargeback rate: ${(chargebackRate * 100).toFixed(1)}%`,
          descriptionAr: `معدل استرداد متوسط: ${(chargebackRate * 100).toFixed(1)}%`,
        });
      }
    }

    // Check refund abuse
    if (userProfile.refundCount > 5) {
      const refundRate = userProfile.refundCount / Math.max(1, userProfile.totalOrders);
      if (refundRate > 0.3) {
        score += 0.3;
        signals.push({
          type: 'HIGH_REFUND',
          score: 0.3,
          description: `High refund rate: ${(refundRate * 100).toFixed(1)}%`,
          descriptionAr: `معدل استرجاع مرتفع: ${(refundRate * 100).toFixed(1)}%`,
        });
      }
    }

    // Account age bonus (negative risk)
    if (userProfile.accountAgeDays > 365 && userProfile.totalOrders > 10) {
      score -= 0.2;
      signals.push({
        type: 'TRUSTED_USER',
        score: -0.2,
        description: 'Established account with good history',
        descriptionAr: 'حساب قديم بسجل جيد',
      });
    }

    // Use existing risk score
    score += userProfile.overallRiskScore / 100 * 0.3;

    return { score: Math.max(0, Math.min(1, score)), signals };
  }

  // ==========================================
  // 🤖 ML MODEL APPLICATION
  // ==========================================

  private async applyMLModel(data: TransactionData): Promise<{ score: number; signals: RiskSignal[] } | null> {
    // Check if ML model is enabled
    const mlRule = await prisma.fraudRule.findFirst({
      where: { ruleType: 'ML_MODEL', isEnabled: true },
    });

    if (!mlRule) return null;

    // In production, this would call an ML service
    // For now, we'll use a simple heuristic model
    const features = {
      amount: data.amount,
      hour: new Date().getHours(),
      dayOfWeek: new Date().getDay(),
      isWeekend: [0, 6].includes(new Date().getDay()),
    };

    // Simple scoring based on time patterns
    let mlScore = 0;
    const signals: RiskSignal[] = [];

    // Late night transactions are riskier
    if (features.hour >= 0 && features.hour <= 5) {
      mlScore += 0.15;
      signals.push({
        type: 'ML_TIME_PATTERN',
        score: 0.15,
        description: 'Late night transaction pattern',
        descriptionAr: 'نمط معاملة في وقت متأخر',
      });
    }

    // Weekend high-value transactions
    if (features.isWeekend && features.amount > 2000) {
      mlScore += 0.1;
      signals.push({
        type: 'ML_WEEKEND_HIGH_VALUE',
        score: 0.1,
        description: 'Weekend high-value pattern',
        descriptionAr: 'نمط قيمة عالية في عطلة نهاية الأسبوع',
      });
    }

    return { score: mlScore, signals };
  }


  // ==========================================
  // 🎚️ RISK LEVEL & DECISION
  // ==========================================

  private getRiskLevel(score: number): RiskLevel {
    if (score >= 80) return 'VERY_HIGH';
    if (score >= 60) return 'HIGH';
    if (score >= 40) return 'MEDIUM';
    if (score >= 20) return 'LOW';
    return 'VERY_LOW';
  }

  private makeDecision(score: number, signals: RiskSignal[]): TransactionDecision {
    // Check for instant decline signals
    const hasBlacklist = signals.some(s => s.type === 'BLACKLIST');
    if (hasBlacklist) return 'DECLINED';

    if (score >= 85) return 'DECLINED';
    if (score >= 70) return 'REVIEW';
    if (score >= 50) return 'CHALLENGE'; // 3DS, OTP, etc.
    return 'APPROVED';
  }

  // ==========================================
  // 🚨 ALERT MANAGEMENT
  // ==========================================

  async createAlert(data: {
    targetType: TargetType;
    targetId: string;
    alertType: AlertType;
    severity: Severity;
    riskScore: number;
    detectedBy: string;
    confidence: number;
    indicators: any;
    rawData?: any;
  }) {
    const alert = await prisma.fraudAlert.create({
      data: {
        targetType: data.targetType,
        targetId: data.targetId,
        alertType: data.alertType,
        severity: data.severity,
        riskScore: data.riskScore,
        detectedBy: data.detectedBy,
        confidence: data.confidence,
        indicators: data.indicators,
        rawData: data.rawData,
        status: 'PENDING',
        actionsTaken: [],
      },
    });

    // Publish to real-time channel
    await redis.publish('fraud:alerts', JSON.stringify(alert));

    // Update metrics
    await this.updateMetrics('alertsGenerated');

    return alert;
  }

  async getAlerts(filters: {
    status?: AlertStatus;
    severity?: Severity;
    targetType?: TargetType;
    startDate?: Date;
    endDate?: Date;
    page?: number;
    limit?: number;
  }) {
    const { page = 1, limit = 20, ...where } = filters;

    const [alerts, total] = await Promise.all([
      prisma.fraudAlert.findMany({
        where: {
          ...(where.status && { status: where.status }),
          ...(where.severity && { severity: where.severity }),
          ...(where.targetType && { targetType: where.targetType }),
          ...(where.startDate && { createdAt: { gte: where.startDate } }),
          ...(where.endDate && { createdAt: { lte: where.endDate } }),
        },
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
      prisma.fraudAlert.count({
        where: {
          ...(where.status && { status: where.status }),
          ...(where.severity && { severity: where.severity }),
          ...(where.targetType && { targetType: where.targetType }),
        },
      }),
    ]);

    return { alerts, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async reviewAlert(alertId: string, data: {
    status: AlertStatus;
    resolution?: string;
    reviewedBy: string;
    actionsTaken?: string[];
  }) {
    const alert = await prisma.fraudAlert.update({
      where: { id: alertId },
      data: {
        status: data.status,
        resolution: data.resolution,
        reviewedBy: data.reviewedBy,
        reviewedAt: new Date(),
        actionsTaken: data.actionsTaken || [],
      },
    });

    // Update metrics
    await this.updateMetrics('alertsResolved');
    if (data.status === 'FALSE_POSITIVE') {
      await this.updateMetrics('falsePositives');
    } else if (data.status === 'CONFIRMED_FRAUD') {
      await this.updateMetrics('confirmedFraud');
    }

    return alert;
  }

  // ==========================================
  // 👤 USER RISK PROFILE
  // ==========================================

  async getUserRiskProfile(userId: string) {
    let profile = await prisma.userRiskProfile.findUnique({
      where: { userId },
      include: { sessions: { take: 10, orderBy: { startedAt: 'desc' } } },
    });

    if (!profile) {
      profile = await prisma.userRiskProfile.create({
        data: {
          userId,
          overallRiskScore: 20, // Default moderate risk for new users
          trustScore: 50,
        },
        include: { sessions: true },
      });
    }

    return profile;
  }

  async updateUserRiskProfile(userId: string, data: Partial<{
    overallRiskScore: number;
    paymentRiskScore: number;
    behaviorRiskScore: number;
    velocityRiskScore: number;
    trustScore: number;
    isBlacklisted: boolean;
    isWhitelisted: boolean;
    requiresReview: boolean;
    knownDevices: string[];
    knownIPs: string[];
    knownLocations: string[];
  }>) {
    return prisma.userRiskProfile.upsert({
      where: { userId },
      update: {
        ...data,
        riskFactors: data.overallRiskScore ? { updatedAt: new Date() } : undefined,
      },
      create: {
        userId,
        ...data,
        riskFactors: {},
      },
    });
  }

  async addKnownDevice(userId: string, deviceId: string) {
    const profile = await this.getUserRiskProfile(userId);
    if (!profile.knownDevices.includes(deviceId)) {
      await prisma.userRiskProfile.update({
        where: { userId },
        data: { knownDevices: { push: deviceId } },
      });
    }
  }

  async addKnownLocation(userId: string, location: string) {
    const profile = await this.getUserRiskProfile(userId);
    if (!profile.knownLocations.includes(location)) {
      await prisma.userRiskProfile.update({
        where: { userId },
        data: { knownLocations: { push: location } },
      });
    }
  }

  // ==========================================
  // 🚫 BLACKLIST MANAGEMENT
  // ==========================================

  async addToBlacklist(data: {
    entryType: BlacklistType;
    value: string;
    reason: string;
    reasonAr?: string;
    source: string;
    relatedAlertId?: string;
    expiresAt?: Date;
    addedBy: string;
  }) {
    return prisma.blacklist.upsert({
      where: {
        entryType_value: {
          entryType: data.entryType,
          value: data.value,
        },
      },
      update: {
        reason: data.reason,
        reasonAr: data.reasonAr,
        isActive: true,
        expiresAt: data.expiresAt,
      },
      create: data,
    });
  }

  async removeFromBlacklist(entryType: BlacklistType, value: string) {
    return prisma.blacklist.updateMany({
      where: { entryType, value },
      data: { isActive: false },
    });
  }

  async checkBlacklist(entryType: BlacklistType, value: string): Promise<boolean> {
    const entry = await prisma.blacklist.findFirst({
      where: {
        entryType,
        value,
        isActive: true,
        OR: [
          { expiresAt: null },
          { expiresAt: { gt: new Date() } },
        ],
      },
    });
    return !!entry;
  }

  // ==========================================
  // 📋 FRAUD RULES
  // ==========================================

  async createRule(data: {
    name: string;
    nameAr?: string;
    description?: string;
    descriptionAr?: string;
    ruleType: RuleType;
    conditions: any;
    actions: any;
    riskWeight?: number;
    createdBy: string;
  }) {
    return prisma.fraudRule.create({ data });
  }

  async updateRule(ruleId: string, data: Partial<{
    name: string;
    nameAr: string;
    description: string;
    descriptionAr: string;
    conditions: any;
    actions: any;
    riskWeight: number;
    isEnabled: boolean;
  }>) {
    return prisma.fraudRule.update({
      where: { id: ruleId },
      data,
    });
  }

  async getRules(filters?: { ruleType?: RuleType; isEnabled?: boolean }) {
    return prisma.fraudRule.findMany({
      where: filters,
      orderBy: { createdAt: 'desc' },
    });
  }

  // ==========================================
  // 📊 ANALYTICS & METRICS
  // ==========================================

  private async updateMetrics(field: 'alertsGenerated' | 'alertsResolved' | 'falsePositives' | 'confirmedFraud' | 'flaggedCount' | 'blockedCount') {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    await prisma.fraudMetrics.upsert({
      where: { date: today },
      update: { [field]: { increment: 1 } },
      create: {
        date: today,
        [field]: 1,
      },
    });
  }

  async getMetrics(startDate: Date, endDate: Date) {
    return prisma.fraudMetrics.findMany({
      where: {
        date: { gte: startDate, lte: endDate },
      },
      orderBy: { date: 'asc' },
    });
  }

  async getDashboardStats() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const weekAgo = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);

    const [todayMetrics, weekMetrics, pendingAlerts, criticalAlerts] = await Promise.all([
      prisma.fraudMetrics.findUnique({ where: { date: today } }),
      prisma.fraudMetrics.aggregate({
        where: { date: { gte: weekAgo } },
        _sum: {
          alertsGenerated: true,
          alertsResolved: true,
          falsePositives: true,
          confirmedFraud: true,
          fraudAmount: true,
          preventedAmount: true,
        },
      }),
      prisma.fraudAlert.count({ where: { status: 'PENDING' } }),
      prisma.fraudAlert.count({ where: { status: 'PENDING', severity: 'CRITICAL' } }),
    ]);

    return {
      today: todayMetrics,
      week: weekMetrics._sum,
      pendingAlerts,
      criticalAlerts,
    };
  }

  // ==========================================
  // 🔧 HELPER METHODS
  // ==========================================

  private async getIPInfo(ipAddress: string): Promise<{
    country?: string;
    city?: string;
    isp?: string;
    isVPN: boolean;
    isProxy: boolean;
    isTor: boolean;
  }> {
    // Check cache first
    const cacheKey = `ip:${ipAddress}`;
    const cached = await redis.get(cacheKey);
    if (cached) return JSON.parse(cached);

    // In production, call IP intelligence service (MaxMind, IPInfo, etc.)
    // For now, return mock data
    const info = {
      country: 'SA',
      city: 'Riyadh',
      isp: 'STC',
      isVPN: false,
      isProxy: false,
      isTor: false,
    };

    // Cache for 1 hour
    await redis.setex(cacheKey, 3600, JSON.stringify(info));
    return info;
  }
}

export const fraudService = new FraudService();
