import { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const prisma = new PrismaClient();

// Zod schemas for validation
const ComplianceAlertSchema = z.object({
  businessAccountId: z.string().uuid(),
  alertType: z.enum(['threshold_breach', 'compliance_violation', 'reporting_deadline', 'data_anomaly', 'regulatory_inquiry']),
  severity: z.enum(['low', 'medium', 'high', 'critical']),
  title: z.string().min(1).max(200),
  description: z.string().min(1),
  jurisdictionCode: z.string().length(2),
  thresholdId: z.string().uuid().optional(),
  metricName: z.string().max(100).optional(),
  currentValue: z.number().optional(),
  thresholdValue: z.number().optional(),
  alertData: z.record(z.any()).default({}),
  autoGenerated: z.boolean().default(true),
  createdBy: z.string().uuid()
});

const ComplianceThresholdSchema = z.object({
  businessAccountId: z.string().uuid(),
  thresholdName: z.string().min(1).max(100),
  thresholdType: z.enum(['ratio', 'absolute', 'percentage', 'count']),
  metricName: z.string().min(1).max(100),
  jurisdictionCode: z.string().length(2),
  minimumValue: z.number().optional(),
  maximumValue: z.number().optional(),
  targetValue: z.number().optional(),
  warningThreshold: z.number().optional(),
  criticalThreshold: z.number().optional(),
  calculationMethod: z.string().min(1),
  effectiveDate: z.string().date(),
  expiryDate: z.string().date().optional(),
  regulatoryReference: z.string().max(200).optional(),
  createdBy: z.string().uuid()
});

const ComplianceMonitoringSchema = z.object({
  businessAccountId: z.string().uuid(),
  thresholdId: z.string().uuid(),
  monitoringDate: z.string().date(),
  currentValue: z.number(),
  thresholdValue: z.number(),
  varianceAmount: z.number(),
  variancePercentage: z.number(),
  complianceStatus: z.enum(['compliant', 'warning', 'critical', 'breach']),
  trendDirection: z.enum(['improving', 'stable', 'deteriorating']).optional(),
  calculationDetails: z.record(z.any()).default({}),
  dataPoints: z.array(z.any()).default([]),
  autoCalculated: z.boolean().default(true)
});

export interface ComplianceAlert {
  id: string;
  businessAccountId: string;
  alertType: string;
  severity: string;
  title: string;
  description: string;
  jurisdictionCode: string;
  thresholdId?: string;
  metricName?: string;
  currentValue?: number;
  thresholdValue?: number;
  varianceAmount?: number;
  variancePercentage?: number;
  alertData: any;
  status: string;
  acknowledgedBy?: string;
  acknowledgedAt?: Date;
  resolutionNotes?: string;
  resolvedBy?: string;
  resolvedAt?: Date;
  autoGenerated: boolean;
  notificationSent: boolean;
  regulatoryNotificationRequired: boolean;
  regulatoryNotificationSent: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceThreshold {
  id: string;
  businessAccountId: string;
  thresholdName: string;
  thresholdType: string;
  metricName: string;
  jurisdictionCode: string;
  minimumValue?: number;
  maximumValue?: number;
  targetValue?: number;
  warningThreshold?: number;
  criticalThreshold?: number;
  calculationMethod: string;
  dataSources: any[];
  isActive: boolean;
  effectiveDate: Date;
  expiryDate?: Date;
  regulatoryReference?: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceMonitoring {
  id: string;
  businessAccountId: string;
  thresholdId: string;
  monitoringDate: Date;
  currentValue: number;
  thresholdValue: number;
  varianceAmount: number;
  variancePercentage: number;
  complianceStatus: string;
  trendDirection?: string;
  calculationDetails: any;
  dataPoints: any[];
  autoCalculated: boolean;
  calculatedAt: Date;
  createdAt: Date;
}

export interface ComplianceMetrics {
  businessAccountId: string;
  jurisdictionCode: string;
  totalThresholds: number;
  activeThresholds: number;
  compliantMetrics: number;
  warningMetrics: number;
  criticalMetrics: number;
  breachedMetrics: number;
  overallComplianceScore: number;
  lastUpdated: Date;
}

export interface ComplianceTrend {
  metricName: string;
  jurisdictionCode: string;
  timeSeries: Array<{
    date: Date;
    value: number;
    threshold: number;
    complianceStatus: string;
  }>;
  trendDirection: string;
  trendStrength: number;
  forecast: Array<{
    date: Date;
    predictedValue: number;
    confidence: number;
  }>;
}

export class ComplianceMonitoringEngine {
  // Compliance Alert Management
  async createComplianceAlert(data: z.infer<typeof ComplianceAlertSchema>): Promise<ComplianceAlert> {
    const validated = ComplianceAlertSchema.parse(data);
    
    const varianceAmount = validated.currentValue && validated.thresholdValue ? 
      validated.currentValue - validated.thresholdValue : 0;
    const variancePercentage = validated.thresholdValue && validated.thresholdValue !== 0 ? 
      (varianceAmount / validated.thresholdValue) * 100 : 0;
    
    const result = await prisma.$queryRaw`
      INSERT INTO regulatory_alerts (
        id,
        business_account_id,
        alert_type,
        severity,
        title,
        description,
        jurisdiction_code,
        threshold_id,
        metric_name,
        current_value,
        threshold_value,
        variance_amount,
        variance_percentage,
        alert_data,
        auto_generated,
        created_by
      ) VALUES (
        ${uuidv4()}::uuid,
        ${validated.businessAccountId}::uuid,
        ${validated.alertType}::varchar,
        ${validated.severity}::varchar,
        ${validated.title}::varchar,
        ${validated.description}::text,
        ${validated.jurisdictionCode}::varchar,
        ${validated.thresholdId || null}::uuid,
        ${validated.metricName || null}::varchar,
        ${validated.currentValue || null}::decimal,
        ${validated.thresholdValue || null}::decimal,
        ${varianceAmount}::decimal,
        ${variancePercentage}::decimal,
        ${JSON.stringify(validated.alertData)}::jsonb,
        ${validated.autoGenerated}::boolean,
        ${validated.createdBy}::uuid
      ) RETURNING id
    `;
    
    const alertId = (result as any)[0]?.id;
    return this.getComplianceAlert(alertId);
  }

  async getComplianceAlert(alertId: string): Promise<ComplianceAlert> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        alert_type as "alertType",
        severity,
        title,
        description,
        jurisdiction_code as "jurisdictionCode",
        threshold_id as "thresholdId",
        metric_name as "metricName",
        current_value as "currentValue",
        threshold_value as "thresholdValue",
        variance_amount as "varianceAmount",
        variance_percentage as "variancePercentage",
        alert_data as "alertData",
        status,
        acknowledged_by as "acknowledgedBy",
        acknowledged_at as "acknowledgedAt",
        resolution_notes as "resolutionNotes",
        resolved_by as "resolvedBy",
        resolved_at as "resolvedAt",
        auto_generated as "autoGenerated",
        notification_sent as "notificationSent",
        regulatory_notification_required as "regulatoryNotificationRequired",
        regulatory_notification_sent as "regulatoryNotificationSent",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_alerts
      WHERE id = ${alertId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getComplianceAlerts(businessAccountId: string, filters: {
    alertType?: string;
    severity?: string;
    status?: string;
    jurisdictionCode?: string;
    limit?: number;
  } = {}): Promise<ComplianceAlert[]> {
    const { alertType, severity, status, jurisdictionCode, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        alert_type as "alertType",
        severity,
        title,
        description,
        jurisdiction_code as "jurisdictionCode",
        threshold_id as "thresholdId",
        metric_name as "metricName",
        current_value as "currentValue",
        threshold_value as "thresholdValue",
        variance_amount as "varianceAmount",
        variance_percentage as "variancePercentage",
        alert_data as "alertData",
        status,
        acknowledged_by as "acknowledgedBy",
        acknowledged_at as "acknowledgedAt",
        resolution_notes as "resolutionNotes",
        resolved_by as "resolvedBy",
        resolved_at as "resolvedAt",
        auto_generated as "autoGenerated",
        notification_sent as "notificationSent",
        regulatory_notification_required as "regulatoryNotificationRequired",
        regulatory_notification_sent as "regulatoryNotificationSent",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_alerts
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (alertType) {
      query += ` AND alert_type = '${alertType}'`;
    }
    
    if (severity) {
      query += ` AND severity = '${severity}'`;
    }
    
    if (status) {
      query += ` AND status = '${status}'`;
    }
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    query += ` ORDER BY created_at DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as ComplianceAlert[];
  }

  // Compliance Threshold Management
  async createComplianceThreshold(data: z.infer<typeof ComplianceThresholdSchema>): Promise<ComplianceThreshold> {
    const validated = ComplianceThresholdSchema.parse(data);
    
    const result = await prisma.$queryRaw`
      INSERT INTO compliance_thresholds (
        id,
        business_account_id,
        threshold_name,
        threshold_type,
        metric_name,
        jurisdiction_code,
        minimum_value,
        maximum_value,
        target_value,
        warning_threshold,
        critical_threshold,
        calculation_method,
        effective_date,
        expiry_date,
        regulatory_reference,
        created_by
      ) VALUES (
        ${uuidv4()}::uuid,
        ${validated.businessAccountId}::uuid,
        ${validated.thresholdName}::varchar,
        ${validated.thresholdType}::varchar,
        ${validated.metricName}::varchar,
        ${validated.jurisdictionCode}::varchar,
        ${validated.minimumValue || null}::decimal,
        ${validated.maximumValue || null}::decimal,
        ${validated.targetValue || null}::decimal,
        ${validated.warningThreshold || null}::decimal,
        ${validated.criticalThreshold || null}::decimal,
        ${validated.calculationMethod}::text,
        ${validated.effectiveDate}::date,
        ${validated.expiryDate || null}::date,
        ${validated.regulatoryReference || null}::varchar,
        ${validated.createdBy}::uuid
      ) RETURNING id
    `;
    
    const thresholdId = (result as any)[0]?.id;
    return this.getComplianceThreshold(thresholdId);
  }

  async getComplianceThreshold(thresholdId: string): Promise<ComplianceThreshold> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        threshold_name as "thresholdName",
        threshold_type as "thresholdType",
        metric_name as "metricName",
        jurisdiction_code as "jurisdictionCode",
        minimum_value as "minimumValue",
        maximum_value as "maximumValue",
        target_value as "targetValue",
        warning_threshold as "warningThreshold",
        critical_threshold as "criticalThreshold",
        calculation_method as "calculationMethod",
        data_sources as "dataSources",
        is_active as "isActive",
        effective_date as "effectiveDate",
        expiry_date as "expiryDate",
        regulatory_reference as "regulatoryReference",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM compliance_thresholds
      WHERE id = ${thresholdId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getComplianceThresholds(businessAccountId: string, filters: {
    jurisdictionCode?: string;
    thresholdType?: string;
    isActive?: boolean;
    limit?: number;
  } = {}): Promise<ComplianceThreshold[]> {
    const { jurisdictionCode, thresholdType, isActive, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        threshold_name as "thresholdName",
        threshold_type as "thresholdType",
        metric_name as "metricName",
        jurisdiction_code as "jurisdictionCode",
        minimum_value as "minimumValue",
        maximum_value as "maximumValue",
        target_value as "targetValue",
        warning_threshold as "warningThreshold",
        critical_threshold as "criticalThreshold",
        calculation_method as "calculationMethod",
        data_sources as "dataSources",
        is_active as "isActive",
        effective_date as "effectiveDate",
        expiry_date as "expiryDate",
        regulatory_reference as "regulatoryReference",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM compliance_thresholds
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    if (thresholdType) {
      query += ` AND threshold_type = '${thresholdType}'`;
    }
    
    if (isActive !== undefined) {
      query += ` AND is_active = ${isActive}`;
    }
    
    query += ` ORDER BY effective_date DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as ComplianceThreshold[];
  }

  // Compliance Monitoring
  async monitorCompliance(
    businessAccountId: string,
    thresholdId: string,
    monitoringDate: Date = new Date()
  ): Promise<ComplianceMonitoring> {
    const threshold = await this.getComplianceThreshold(thresholdId);
    if (!threshold) {
      throw new Error('Threshold not found');
    }
    
    // Calculate current value based on threshold calculation method
    const currentValue = await this.calculateMetricValue(
      businessAccountId,
      threshold.metricName,
      threshold.calculationMethod
    );
    
    const varianceAmount = currentValue - (threshold.targetValue || 0);
    const variancePercentage = threshold.targetValue && threshold.targetValue !== 0 ? 
      (varianceAmount / threshold.targetValue) * 100 : 0;
    
    // Determine compliance status
    let complianceStatus: string = 'compliant';
    if (threshold.minimumValue && currentValue < threshold.minimumValue) {
      complianceStatus = 'breach';
    } else if (threshold.maximumValue && currentValue > threshold.maximumValue) {
      complianceStatus = 'breach';
    } else if (threshold.criticalThreshold && 
               (currentValue < threshold.criticalThreshold || currentValue > threshold.criticalThreshold)) {
      complianceStatus = 'critical';
    } else if (threshold.warningThreshold && 
               (currentValue < threshold.warningThreshold || currentValue > threshold.warningThreshold)) {
      complianceStatus = 'warning';
    }
    
    // Calculate trend direction
    const trendDirection = await this.calculateTrendDirection(
      businessAccountId,
      threshold.metricName,
      currentValue
    );
    
    const result = await prisma.$queryRaw`
      INSERT INTO compliance_monitoring (
        id,
        business_account_id,
        threshold_id,
        monitoring_date,
        current_value,
        threshold_value,
        variance_amount,
        variance_percentage,
        compliance_status,
        trend_direction,
        calculation_details,
        data_points,
        auto_calculated
      ) VALUES (
        ${uuidv4()}::uuid,
        ${businessAccountId}::uuid,
        ${thresholdId}::uuid,
        ${monitoringDate}::date,
        ${currentValue}::decimal,
        ${threshold.targetValue || 0}::decimal,
        ${varianceAmount}::decimal,
        ${variancePercentage}::decimal,
        ${complianceStatus}::varchar,
        ${trendDirection || null}::varchar,
        ${JSON.stringify({
          thresholdName: threshold.thresholdName,
          calculationMethod: threshold.calculationMethod,
          regulatoryReference: threshold.regulatoryReference
        })}::jsonb,
        '[]'::jsonb,
        true::boolean
      ) RETURNING id
    `;
    
    const monitoringId = (result as any)[0]?.id;
    return this.getComplianceMonitoring(monitoringId);
  }

  async getComplianceMonitoring(monitoringId: string): Promise<ComplianceMonitoring> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        threshold_id as "thresholdId",
        monitoring_date as "monitoringDate",
        current_value as "currentValue",
        threshold_value as "thresholdValue",
        variance_amount as "varianceAmount",
        variance_percentage as "variancePercentage",
        compliance_status as "complianceStatus",
        trend_direction as "trendDirection",
        calculation_details as "calculationDetails",
        data_points as "dataPoints",
        auto_calculated as "autoCalculated",
        calculated_at as "calculatedAt",
        created_at as "createdAt"
      FROM compliance_monitoring
      WHERE id = ${monitoringId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getComplianceMonitoringHistory(
    businessAccountId: string,
    thresholdId: string,
    days: number = 30
  ): Promise<ComplianceMonitoring[]> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        threshold_id as "thresholdId",
        monitoring_date as "monitoringDate",
        current_value as "currentValue",
        threshold_value as "thresholdValue",
        variance_amount as "varianceAmount",
        variance_percentage as "variancePercentage",
        compliance_status as "complianceStatus",
        trend_direction as "trendDirection",
        calculation_details as "calculationDetails",
        data_points as "dataPoints",
        auto_calculated as "autoCalculated",
        calculated_at as "calculatedAt",
        created_at as "createdAt"
      FROM compliance_monitoring
      WHERE business_account_id = ${businessAccountId}::uuid
        AND threshold_id = ${thresholdId}::uuid
        AND monitoring_date >= CURRENT_DATE - INTERVAL '${days} days'
      ORDER BY monitoring_date DESC
    `;
    
    return result as ComplianceMonitoring[];
  }

  // Automated Compliance Monitoring
  async runComplianceMonitoring(businessAccountId: string): Promise<ComplianceMonitoring[]> {
    const thresholds = await this.getComplianceThresholds(businessAccountId, { isActive: true });
    const monitoringResults: ComplianceMonitoring[] = [];
    
    for (const threshold of thresholds) {
      try {
        const monitoring = await this.monitorCompliance(businessAccountId, threshold.id);
        monitoringResults.push(monitoring);
        
        // Create alert if non-compliant
        if (monitoring.complianceStatus !== 'compliant') {
          await this.createComplianceAlert({
            businessAccountId,
            alertType: 'threshold_breach',
            severity: monitoring.complianceStatus === 'breach' ? 'critical' : 'high',
            title: `Compliance Threshold Breach: ${threshold.thresholdName}`,
            description: `${threshold.metricName} threshold breached. Current value: ${monitoring.currentValue}, Threshold: ${monitoring.thresholdValue}`,
            jurisdictionCode: threshold.jurisdictionCode,
            thresholdId: threshold.id,
            metricName: threshold.metricName,
            currentValue: monitoring.currentValue,
            thresholdValue: monitoring.thresholdValue,
            alertData: {
              thresholdName: threshold.thresholdName,
              calculationMethod: threshold.calculationMethod,
              varianceAmount: monitoring.varianceAmount,
              variancePercentage: monitoring.variancePercentage
            },
            autoGenerated: true,
            createdBy: 'system'
          });
        }
      } catch (error) {
        console.error(`Error monitoring threshold ${threshold.id}:`, error);
      }
    }
    
    return monitoringResults;
  }

  // Compliance Analytics
  async getComplianceMetrics(businessAccountId: string): Promise<ComplianceMetrics> {
    const thresholds = await this.getComplianceThresholds(businessAccountId);
    const activeThresholds = thresholds.filter(t => t.isActive);
    
    // Get current compliance status for all active thresholds
    const today = new Date();
    const currentMonitoring: ComplianceMonitoring[] = [];
    
    for (const threshold of activeThresholds) {
      try {
        const monitoring = await this.monitorCompliance(businessAccountId, threshold.id, today);
        currentMonitoring.push(monitoring);
      } catch (error) {
        console.error(`Error getting current monitoring for threshold ${threshold.id}:`, error);
      }
    }
    
    const compliantMetrics = currentMonitoring.filter(m => m.complianceStatus === 'compliant').length;
    const warningMetrics = currentMonitoring.filter(m => m.complianceStatus === 'warning').length;
    const criticalMetrics = currentMonitoring.filter(m => m.complianceStatus === 'critical').length;
    const breachedMetrics = currentMonitoring.filter(m => m.complianceStatus === 'breach').length;
    
    const overallComplianceScore = activeThresholds.length > 0 ? 
      (compliantMetrics / activeThresholds.length) * 100 : 100;
    
    return {
      businessAccountId,
      jurisdictionCode: 'ALL', // Aggregate across all jurisdictions
      totalThresholds: thresholds.length,
      activeThresholds: activeThresholds.length,
      compliantMetrics,
      warningMetrics,
      criticalMetrics,
      breachedMetrics,
      overallComplianceScore,
      lastUpdated: new Date()
    };
  }

  async getComplianceTrends(
    businessAccountId: string,
    metricName: string,
    jurisdictionCode: string,
    days: number = 90
  ): Promise<ComplianceTrend> {
    const threshold = await this.getComplianceThresholds(businessAccountId, {
      metricName,
      jurisdictionCode,
      limit: 1
    });
    
    if (threshold.length === 0) {
      throw new Error('No threshold found for the specified metric and jurisdiction');
    }
    
    const monitoringHistory = await this.getComplianceMonitoringHistory(
      businessAccountId,
      threshold[0].id,
      days
    );
    
    const timeSeries = monitoringHistory.map(m => ({
      date: m.monitoringDate,
      value: m.currentValue,
      threshold: m.thresholdValue,
      complianceStatus: m.complianceStatus
    }));
    
    const trendDirection = this.calculateTrendFromSeries(timeSeries);
    const trendStrength = this.calculateTrendStrength(timeSeries);
    const forecast = await this.generateComplianceForecast(timeSeries, 7);
    
    return {
      metricName,
      jurisdictionCode,
      timeSeries,
      trendDirection,
      trendStrength,
      forecast
    };
  }

  // Helper Methods
  private async calculateMetricValue(
    businessAccountId: string,
    metricName: string,
    calculationMethod: string
  ): Promise<number> {
    // This would integrate with actual business data
    // For now, return placeholder values based on metric type
    
    switch (metricName.toLowerCase()) {
      case 'capital_adequacy_ratio':
        return 15.5; // Placeholder
      case 'liquidity_coverage_ratio':
        return 125.3; // Placeholder
      case 'large_exposure_limit':
        return 18.2; // Placeholder
      case 'risk_weighted_assets':
        return 850000000; // Placeholder
      default:
        return 100; // Placeholder
    }
  }

  private async calculateTrendDirection(
    businessAccountId: string,
    metricName: string,
    currentValue: number
  ): Promise<string> {
    // Get historical values to determine trend
    const historicalData = await this.getHistoricalMetricValues(
      businessAccountId,
      metricName,
      7 // Last 7 days
    );
    
    if (historicalData.length < 2) return 'stable';
    
    const recentValues = historicalData.slice(-3); // Last 3 values
    const trend = recentValues[recentValues.length - 1] - recentValues[0];
    const threshold = Math.abs(currentValue) * 0.02; // 2% threshold
    
    if (trend > threshold) return 'improving';
    if (trend < -threshold) return 'deteriorating';
    return 'stable';
  }

  private async getHistoricalMetricValues(
    businessAccountId: string,
    metricName: string,
    days: number
  ): Promise<number[]> {
    // This would get actual historical data
    // For now, return placeholder data
    const values: number[] = [];
    for (let i = 0; i < days; i++) {
      values.push(100 + Math.random() * 20 - 10); // Random variation around 100
    }
    return values;
  }

  private calculateTrendFromSeries(timeSeries: any[]): string {
    if (timeSeries.length < 2) return 'stable';
    
    const firstValue = timeSeries[0].value;
    const lastValue = timeSeries[timeSeries.length - 1].value;
    const change = (lastValue - firstValue) / firstValue * 100;
    
    if (Math.abs(change) < 2) return 'stable';
    return change > 0 ? 'improving' : 'deteriorating';
  }

  private calculateTrendStrength(timeSeries: any[]): number {
    if (timeSeries.length < 3) return 0;
    
    // Simple linear regression to calculate trend strength
    const n = timeSeries.length;
    const x = Array.from({ length: n }, (_, i) => i);
    const y = timeSeries.map(point => point.value);
    
    const sumX = x.reduce((a, b) => a + b, 0);
    const sumY = y.reduce((a, b) => a + b, 0);
    const sumXY = x.reduce((sum, xi, i) => sum + xi * y[i], 0);
    const sumX2 = x.reduce((sum, xi) => sum + xi * xi, 0);
    
    const slope = (n * sumXY - sumX * sumY) / (n * sumX2 - sumX * sumX);
    
    return Math.abs(slope) * 100; // Normalize to percentage
  }

  private async generateComplianceForecast(
    timeSeries: any[],
    days: number
  ): Promise<Array<{ date: Date; predictedValue: number; confidence: number }>> {
    // Simple linear forecast
    if (timeSeries.length < 2) return [];
    
    const values = timeSeries.map(point => point.value);
    const n = values.length;
    const x = Array.from({ length: n }, (_, i) => i);
    
    const sumX = x.reduce((a, b) => a + b, 0);
    const sumY = values.reduce((a, b) => a + b, 0);
    const sumXY = x.reduce((sum, xi, i) => sum + xi * values[i], 0);
    const sumX2 = x.reduce((sum, xi) => sum + xi * xi, 0);
    
    const slope = (n * sumXY - sumX * sumY) / (n * sumX2 - sumX * sumX);
    const intercept = (sumY - slope * sumX) / n;
    
    const forecast = [];
    const lastDate = new Date(timeSeries[timeSeries.length - 1].date);
    
    for (let i = 1; i <= days; i++) {
      const predictedValue = slope * (n + i - 1) + intercept;
      const confidence = Math.max(0, 100 - (i * 10)); // Decreasing confidence
      
      forecast.push({
        date: new Date(lastDate.getTime() + i * 24 * 60 * 60 * 1000),
        predictedValue,
        confidence
      });
    }
    
    return forecast;
  }

  // Automated Alert Generation
  async generateComplianceAlerts(businessAccountId: string): Promise<ComplianceAlert[]> {
    const alerts: ComplianceAlert[] = [];
    const metrics = await this.getComplianceMetrics(businessAccountId);
    
    // Generate alerts for critical compliance issues
    if (metrics.overallComplianceScore < 50) {
      const alert = await this.createComplianceAlert({
        businessAccountId,
        alertType: 'compliance_violation',
        severity: 'critical',
        title: 'Critical Compliance Score',
        description: `Overall compliance score is ${metrics.overallComplianceScore.toFixed(2)}%`,
        jurisdictionCode: 'ALL',
        currentValue: metrics.overallComplianceScore,
        thresholdValue: 80,
        alertData: {
          totalThresholds: metrics.totalThresholds,
          activeThresholds: metrics.activeThresholds,
          breachedMetrics: metrics.breachedMetrics
        },
        autoGenerated: true,
        createdBy: 'system'
      });
      alerts.push(alert);
    }
    
    // Generate alerts for individual threshold breaches
    const monitoring = await this.runComplianceMonitoring(businessAccountId);
    const criticalMonitoring = monitoring.filter(m => m.complianceStatus === 'critical' || m.complianceStatus === 'breach');
    
    for (const cm of criticalMonitoring) {
      const threshold = await this.getComplianceThreshold(cm.thresholdId);
      const alert = await this.createComplianceAlert({
        businessAccountId,
        alertType: 'threshold_breach',
        severity: cm.complianceStatus === 'breach' ? 'critical' : 'high',
        title: `Threshold Breach: ${threshold.thresholdName}`,
        description: `${threshold.metricName} has ${cm.complianceStatus} status`,
        jurisdictionCode: threshold.jurisdictionCode,
        thresholdId: threshold.id,
        metricName: threshold.metricName,
        currentValue: cm.currentValue,
        thresholdValue: cm.thresholdValue,
        alertData: {
          varianceAmount: cm.varianceAmount,
          variancePercentage: cm.variancePercentage,
          trendDirection: cm.trendDirection
        },
        autoGenerated: true,
        createdBy: 'system'
      });
      alerts.push(alert);
    }
    
    return alerts;
  }

  // Compliance Dashboard
  async getComplianceDashboard(businessAccountId: string, language: 'en' | 'ar' = 'en'): Promise<any> {
    const metrics = await this.getComplianceMetrics(businessAccountId);
    const recentAlerts = await this.getComplianceAlerts(businessAccountId, { limit: 10 });
    const activeThresholds = await this.getComplianceThresholds(businessAccountId, { isActive: true });
    
    return {
      summary: language === 'ar' ? {
        dashboardTitle: 'لوحة معلومات الامتثال',
        overallComplianceScore: metrics.overallComplianceScore,
        totalThresholds: metrics.totalThresholds,
        activeThresholds: metrics.activeThresholds,
        compliantMetrics: metrics.compliantMetrics,
        nonCompliantMetrics: metrics.activeThresholds - metrics.compliantMetrics,
        criticalAlerts: recentAlerts.filter(a => a.severity === 'critical').length,
        generatedAt: new Date().toISOString()
      } : {
        dashboardTitle: 'Compliance Dashboard',
        overallComplianceScore: metrics.overallComplianceScore,
        totalThresholds: metrics.totalThresholds,
        activeThresholds: metrics.activeThresholds,
        compliantMetrics: metrics.compliantMetrics,
        nonCompliantMetrics: metrics.activeThresholds - metrics.compliantMetrics,
        criticalAlerts: recentAlerts.filter(a => a.severity === 'critical').length,
        generatedAt: new Date().toISOString()
      },
      metrics,
      recentAlerts,
      activeThresholds,
      recommendations: this.generateComplianceRecommendations(metrics, recentAlerts, language)
    };
  }

  private generateComplianceRecommendations(
    metrics: ComplianceMetrics,
    alerts: ComplianceAlert[],
    language: 'en' | 'ar'
  ): string[] {
    const recommendations = [];
    
    if (metrics.overallComplianceScore < 80) {
      recommendations.push(language === 'ar' ? 
        'درجة الامتثال منخفضة - راجع جميع العتبات الحريرة' : 
        'Low compliance score - review all critical thresholds'
      );
    }
    
    if (metrics.breachedMetrics > 0) {
      recommendations.push(language === 'ar' ? 
        `هناك ${metrics.breachedMetrics} عتبات منتهكة - اتخذ إجراءات فورية` : 
        `${metrics.breachedMetrics} thresholds breached - take immediate action`
      );
    }
    
    const criticalAlerts = alerts.filter(a => a.severity === 'critical');
    if (criticalAlerts.length > 0) {
      recommendations.push(language === 'ar' ? 
        `هناك ${criticalAlerts.length} تنبيهات حريرة - أولوية عالية` : 
        `${criticalAlerts.length} critical alerts - high priority`
      );
    }
    
    return recommendations;
  }
}
