import { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const prisma = new PrismaClient();

// Zod schemas for validation
const RegulatoryReportSchema = z.object({
  businessAccountId: z.string().uuid(),
  reportName: z.string().min(1).max(200),
  reportType: z.enum(['capital_adequacy', 'liquidity_coverage', 'large_exposures', 'risk_weighted_assets', 'stress_testing']),
  jurisdictionCode: z.string().length(2),
  reportingPeriodStart: z.string().date(),
  reportingPeriodEnd: z.string().date(),
  reportTemplate: z.record(z.any()),
  autoGenerated: z.boolean().default(true),
  createdBy: z.string().uuid()
});

const ComplianceThresholdSchema = z.object({
  businessAccountId: z.string().uuid(),
  thresholdName: z.string().min(1).max(100),
  thresholdType: z.enum(['ratio', 'absolute', 'percentage', 'count']),
  metricName: z.string().min(1).max(100),
  jurisdictionCode: z.string().length(2),
  minimumValue: z.number().optional(),
  maximumValue: z.number().optional(),
  targetValue: z.number().optional(),
  warningThreshold: z.number().optional(),
  criticalThreshold: z.number().optional(),
  calculationMethod: z.string().min(1),
  effectiveDate: z.string().date(),
  expiryDate: z.string().date().optional(),
  regulatoryReference: z.string().max(200).optional(),
  createdBy: z.string().uuid()
});

const RegulatoryKPISchema = z.object({
  businessAccountId: z.string().uuid(),
  kpiName: z.string().min(1).max(100),
  kpiCategory: z.enum(['capital', 'liquidity', 'credit_risk', 'market_risk', 'operational_risk']),
  jurisdictionCode: z.string().length(2),
  kpiValue: z.number(),
  kpiUnit: z.enum(['percentage', 'ratio', 'currency', 'count']).optional(),
  targetValue: z.number().optional(),
  benchmarkValue: z.number().optional(),
  measurementDate: z.string().date(),
  periodType: z.enum(['daily', 'weekly', 'monthly', 'quarterly']),
  calculationMethod: z.string().min(1),
  confidenceLevel: z.number().int().min(1).max(5).default(3),
  isRealTime: z.boolean().default(false),
  createdBy: z.string().uuid()
});

export interface RegulatoryReport {
  id: string;
  businessAccountId: string;
  reportName: string;
  reportType: string;
  jurisdictionCode: string;
  reportingPeriodStart: Date;
  reportingPeriodEnd: Date;
  reportTemplate: any;
  generatedData: any;
  status: string;
  submittedBy?: string;
  submittedAt?: Date;
  approvedBy?: string;
  approvedAt?: Date;
  submissionReference?: string;
  regulatoryComments?: string;
  complianceScore?: number;
  autoGenerated: boolean;
  generationTimeMs?: number;
  filePath?: string;
  fileHash?: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceThreshold {
  id: string;
  businessAccountId: string;
  thresholdName: string;
  thresholdType: string;
  metricName: string;
  jurisdictionCode: string;
  minimumValue?: number;
  maximumValue?: number;
  targetValue?: number;
  warningThreshold?: number;
  criticalThreshold?: number;
  calculationMethod: string;
  dataSources: any[];
  isActive: boolean;
  effectiveDate: Date;
  expiryDate?: Date;
  regulatoryReference?: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface RegulatoryKPI {
  id: string;
  businessAccountId: string;
  kpiName: string;
  kpiCategory: string;
  jurisdictionCode: string;
  kpiValue: number;
  kpiUnit?: string;
  targetValue?: number;
  benchmarkValue?: number;
  varianceFromTarget?: number;
  trendDirection?: string;
  performanceRating?: string;
  measurementDate: Date;
  periodType: string;
  calculationMethod: string;
  dataSources: any[];
  confidenceLevel: number;
  isRealTime: boolean;
  lastUpdated: Date;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface RegulatoryAlert {
  id: string;
  businessAccountId: string;
  alertType: string;
  severity: string;
  title: string;
  description: string;
  jurisdictionCode: string;
  thresholdId?: string;
  metricName?: string;
  currentValue?: number;
  thresholdValue?: number;
  varianceAmount?: number;
  variancePercentage?: number;
  alertData: any;
  status: string;
  acknowledgedBy?: string;
  acknowledgedAt?: Date;
  resolutionNotes?: string;
  resolvedBy?: string;
  resolvedAt?: Date;
  autoGenerated: boolean;
  notificationSent: boolean;
  regulatoryNotificationRequired: boolean;
  regulatoryNotificationSent: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface RegulatorySnapshot {
  id: string;
  businessAccountId: string;
  snapshotName: string;
  snapshotDescription?: string;
  snapshotDate: Date;
  snapshotType: string;
  jurisdictionCode: string;
  snapshotData: any;
  includesKpis: boolean;
  includesReports: boolean;
  includesAlerts: boolean;
  includesThresholds: boolean;
  isReadOnly: boolean;
  isImmutable: boolean;
  retentionPeriodDays: number;
  accessCount: number;
  lastAccessed?: Date;
  createdBy: string;
  createdAt: Date;
}

export interface DataFeed {
  id: string;
  businessAccountId: string;
  feedName: string;
  feedType: string;
  targetSystem: string;
  jurisdictionCode: string;
  feedFormat: string;
  feedFrequency: string;
  dataSchema: any;
  endpointUrl?: string;
  authenticationMethod?: string;
  authenticationConfig?: any;
  isActive: boolean;
  lastTransmission?: Date;
  transmissionCount: number;
  errorCount: number;
  lastError?: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export class RegulatoryReportingEngine {
  // Regulatory Report Generation
  async generateRegulatoryReport(data: z.infer<typeof RegulatoryReportSchema>): Promise<RegulatoryReport> {
    const validated = RegulatoryReportSchema.parse(data);
    
    const result = await prisma.$queryRaw`
      SELECT generate_regulatory_report(
        ${validated.businessAccountId}::uuid,
        ${validated.reportType}::varchar,
        ${validated.jurisdictionCode}::varchar,
        ${validated.reportingPeriodStart}::date,
        ${validated.reportingPeriodEnd}::date,
        ${validated.autoGenerated}::boolean
      ) as report_id
    `;
    
    const reportId = (result as any)[0]?.report_id;
    return this.getRegulatoryReport(reportId);
  }

  async getRegulatoryReport(reportId: string): Promise<RegulatoryReport> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        report_name as "reportName",
        report_type as "reportType",
        jurisdiction_code as "jurisdictionCode",
        reporting_period_start as "reportingPeriodStart",
        reporting_period_end as "reportingPeriodEnd",
        report_template as "reportTemplate",
        generated_data as "generatedData",
        status,
        submitted_by as "submittedBy",
        submitted_at as "submittedAt",
        approved_by as "approvedBy",
        approved_at as "approvedAt",
        submission_reference as "submissionReference",
        regulatory_comments as "regulatoryComments",
        compliance_score as "complianceScore",
        auto_generated as "autoGenerated",
        generation_time_ms as "generationTimeMs",
        file_path as "filePath",
        file_hash as "fileHash",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_reports
      WHERE id = ${reportId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getRegulatoryReports(businessAccountId: string, filters: {
    reportType?: string;
    jurisdictionCode?: string;
    status?: string;
    startDate?: string;
    endDate?: string;
    limit?: number;
  } = {}): Promise<RegulatoryReport[]> {
    const { reportType, jurisdictionCode, status, startDate, endDate, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        report_name as "reportName",
        report_type as "reportType",
        jurisdiction_code as "jurisdictionCode",
        reporting_period_start as "reportingPeriodStart",
        reporting_period_end as "reportingPeriodEnd",
        report_template as "reportTemplate",
        generated_data as "generatedData",
        status,
        submitted_by as "submittedBy",
        submitted_at as "submittedAt",
        approved_by as "approvedBy",
        approved_at as "approvedAt",
        submission_reference as "submissionReference",
        regulatory_comments as "regulatoryComments",
        compliance_score as "complianceScore",
        auto_generated as "autoGenerated",
        generation_time_ms as "generationTimeMs",
        file_path as "filePath",
        file_hash as "fileHash",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_reports
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (reportType) {
      query += ` AND report_type = '${reportType}'`;
    }
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    if (status) {
      query += ` AND status = '${status}'`;
    }
    
    if (startDate) {
      query += ` AND reporting_period_start >= '${startDate}'::date`;
    }
    
    if (endDate) {
      query += ` AND reporting_period_end <= '${endDate}'::date`;
    }
    
    query += ` ORDER BY reporting_period_end DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as RegulatoryReport[];
  }

  // Compliance Threshold Management
  async createComplianceThreshold(data: z.infer<typeof ComplianceThresholdSchema>): Promise<ComplianceThreshold> {
    const validated = ComplianceThresholdSchema.parse(data);
    
    const result = await prisma.$queryRaw`
      INSERT INTO compliance_thresholds (
        id,
        business_account_id,
        threshold_name,
        threshold_type,
        metric_name,
        jurisdiction_code,
        minimum_value,
        maximum_value,
        target_value,
        warning_threshold,
        critical_threshold,
        calculation_method,
        effective_date,
        expiry_date,
        regulatory_reference,
        created_by
      ) VALUES (
        ${uuidv4()}::uuid,
        ${validated.businessAccountId}::uuid,
        ${validated.thresholdName}::varchar,
        ${validated.thresholdType}::varchar,
        ${validated.metricName}::varchar,
        ${validated.jurisdictionCode}::varchar,
        ${validated.minimumValue || null}::decimal,
        ${validated.maximumValue || null}::decimal,
        ${validated.targetValue || null}::decimal,
        ${validated.warningThreshold || null}::decimal,
        ${validated.criticalThreshold || null}::decimal,
        ${validated.calculationMethod}::text,
        ${validated.effectiveDate}::date,
        ${validated.expiryDate || null}::date,
        ${validated.regulatoryReference || null}::varchar,
        ${validated.createdBy}::uuid
      ) RETURNING id
    `;
    
    const thresholdId = (result as any)[0]?.id;
    return this.getComplianceThreshold(thresholdId);
  }

  async getComplianceThreshold(thresholdId: string): Promise<ComplianceThreshold> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        threshold_name as "thresholdName",
        threshold_type as "thresholdType",
        metric_name as "metricName",
        jurisdiction_code as "jurisdictionCode",
        minimum_value as "minimumValue",
        maximum_value as "maximumValue",
        target_value as "targetValue",
        warning_threshold as "warningThreshold",
        critical_threshold as "criticalThreshold",
        calculation_method as "calculationMethod",
        data_sources as "dataSources",
        is_active as "isActive",
        effective_date as "effectiveDate",
        expiry_date as "expiryDate",
        regulatory_reference as "regulatoryReference",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM compliance_thresholds
      WHERE id = ${thresholdId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getComplianceThresholds(businessAccountId: string, filters: {
    jurisdictionCode?: string;
    thresholdType?: string;
    isActive?: boolean;
    limit?: number;
  } = {}): Promise<ComplianceThreshold[]> {
    const { jurisdictionCode, thresholdType, isActive, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        threshold_name as "thresholdName",
        threshold_type as "thresholdType",
        metric_name as "metricName",
        jurisdiction_code as "jurisdictionCode",
        minimum_value as "minimumValue",
        maximum_value as "maximumValue",
        target_value as "targetValue",
        warning_threshold as "warningThreshold",
        critical_threshold as "criticalThreshold",
        calculation_method as "calculationMethod",
        data_sources as "dataSources",
        is_active as "isActive",
        effective_date as "effectiveDate",
        expiry_date as "expiryDate",
        regulatory_reference as "regulatoryReference",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM compliance_thresholds
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    if (thresholdType) {
      query += ` AND threshold_type = '${thresholdType}'`;
    }
    
    if (isActive !== undefined) {
      query += ` AND is_active = ${isActive}`;
    }
    
    query += ` ORDER BY effective_date DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as ComplianceThreshold[];
  }

  // Regulatory KPI Management
  async createRegulatoryKPI(data: z.infer<typeof RegulatoryKPISchema>): Promise<RegulatoryKPI> {
    const validated = RegulatoryKPISchema.parse(data);
    
    const varianceFromTarget = validated.targetValue ? validated.kpiValue - validated.targetValue : undefined;
    const performanceRating = this.calculatePerformanceRating(validated.kpiValue, validated.targetValue);
    const trendDirection = await this.calculateTrendDirection(
      validated.businessAccountId,
      validated.kpiName,
      validated.kpiValue
    );
    
    const result = await prisma.$queryRaw`
      INSERT INTO regulatory_kpis (
        id,
        business_account_id,
        kpi_name,
        kpi_category,
        jurisdiction_code,
        kpi_value,
        kpi_unit,
        target_value,
        benchmark_value,
        variance_from_target,
        trend_direction,
        performance_rating,
        measurement_date,
        period_type,
        calculation_method,
        data_sources,
        confidence_level,
        is_real_time,
        created_by
      ) VALUES (
        ${uuidv4()}::uuid,
        ${validated.businessAccountId}::uuid,
        ${validated.kpiName}::varchar,
        ${validated.kpiCategory}::varchar,
        ${validated.jurisdictionCode}::varchar,
        ${validated.kpiValue}::decimal,
        ${validated.kpiUnit || null}::varchar,
        ${validated.targetValue || null}::decimal,
        ${validated.benchmarkValue || null}::decimal,
        ${varianceFromTarget || null}::decimal,
        ${trendDirection || null}::varchar,
        ${performanceRating || null}::varchar,
        ${validated.measurementDate}::date,
        ${validated.periodType}::varchar,
        ${validated.calculationMethod}::text,
        '[]'::jsonb,
        ${validated.confidenceLevel}::integer,
        ${validated.isRealTime}::boolean,
        ${validated.createdBy}::uuid
      ) RETURNING id
    `;
    
    const kpiId = (result as any)[0]?.id;
    return this.getRegulatoryKPI(kpiId);
  }

  async getRegulatoryKPI(kpiId: string): Promise<RegulatoryKPI> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        kpi_name as "kpiName",
        kpi_category as "kpiCategory",
        jurisdiction_code as "jurisdictionCode",
        kpi_value as "kpiValue",
        kpi_unit as "kpiUnit",
        target_value as "targetValue",
        benchmark_value as "benchmarkValue",
        variance_from_target as "varianceFromTarget",
        trend_direction as "trendDirection",
        performance_rating as "performanceRating",
        measurement_date as "measurementDate",
        period_type as "periodType",
        calculation_method as "calculationMethod",
        data_sources as "dataSources",
        confidence_level as "confidenceLevel",
        is_real_time as "isRealTime",
        last_updated as "lastUpdated",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_kpis
      WHERE id = ${kpiId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getRegulatoryKPIs(businessAccountId: string, filters: {
    kpiCategory?: string;
    jurisdictionCode?: string;
    periodType?: string;
    isRealTime?: boolean;
    measurementDate?: string;
    limit?: number;
  } = {}): Promise<RegulatoryKPI[]> {
    const { kpiCategory, jurisdictionCode, periodType, isRealTime, measurementDate, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        kpi_name as "kpiName",
        kpi_category as "kpiCategory",
        jurisdiction_code as "jurisdictionCode",
        kpi_value as "kpiValue",
        kpi_unit as "kpiUnit",
        target_value as "targetValue",
        benchmark_value as "benchmarkValue",
        variance_from_target as "varianceFromTarget",
        trend_direction as "trendDirection",
        performance_rating as "performanceRating",
        measurement_date as "measurementDate",
        period_type as "periodType",
        calculation_method as "calculationMethod",
        data_sources as "dataSources",
        confidence_level as "confidenceLevel",
        is_real_time as "isRealTime",
        last_updated as "lastUpdated",
        created_by as "createdBy",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_kpis
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (kpiCategory) {
      query += ` AND kpi_category = '${kpiCategory}'`;
    }
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    if (periodType) {
      query += ` AND period_type = '${periodType}'`;
    }
    
    if (isRealTime !== undefined) {
      query += ` AND is_real_time = ${isRealTime}`;
    }
    
    if (measurementDate) {
      query += ` AND measurement_date = '${measurementDate}'::date`;
    }
    
    query += ` ORDER BY measurement_date DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as RegulatoryKPI[];
  }

  // Compliance Monitoring
  async monitorCompliance(businessAccountId: string, thresholdId: string): Promise<void> {
    await prisma.$queryRaw`
      SELECT calculate_compliance_status(
        ${businessAccountId}::uuid,
        ${thresholdId}::uuid,
        CURRENT_DATE
      )
    `;
  }

  async monitorAllCompliance(businessAccountId: string): Promise<void> {
    const thresholds = await this.getComplianceThresholds(businessAccountId, { isActive: true });
    
    for (const threshold of thresholds) {
      await this.monitorCompliance(businessAccountId, threshold.id);
    }
  }

  // Regulatory Snapshots
  async createRegulatorySnapshot(
    businessAccountId: string,
    snapshotName: string,
    snapshotType: string,
    jurisdictionCode: string,
    createdBy: string,
    options: {
      includesKpis?: boolean;
      includesReports?: boolean;
      includesAlerts?: boolean;
      includesThresholds?: boolean;
      snapshotDescription?: string;
    } = {}
  ): Promise<RegulatorySnapshot> {
    const {
      includesKpis = true,
      includesReports = true,
      includesAlerts = true,
      includesThresholds = true,
      snapshotDescription
    } = options;
    
    const snapshotData = await this.gatherSnapshotData(
      businessAccountId,
      jurisdictionCode,
      { includesKpis, includesReports, includesAlerts, includesThresholds }
    );
    
    const result = await prisma.$queryRaw`
      INSERT INTO regulatory_snapshots (
        id,
        business_account_id,
        snapshot_name,
        snapshot_description,
        snapshot_date,
        snapshot_type,
        jurisdiction_code,
        snapshot_data,
        includes_kpis,
        includes_reports,
        includes_alerts,
        includes_thresholds,
        is_read_only,
        is_immutable,
        created_by
      ) VALUES (
        ${uuidv4()}::uuid,
        ${businessAccountId}::uuid,
        ${snapshotName}::varchar,
        ${snapshotDescription || null}::text,
        CURRENT_TIMESTAMP,
        ${snapshotType}::varchar,
        ${jurisdictionCode}::varchar,
        ${JSON.stringify(snapshotData)}::jsonb,
        ${includesKpis}::boolean,
        ${includesReports}::boolean,
        ${includesAlerts}::boolean,
        ${includesThresholds}::boolean,
        true::boolean,
        true::boolean,
        ${createdBy}::uuid
      ) RETURNING id
    `;
    
    const snapshotId = (result as any)[0]?.id;
    return this.getRegulatorySnapshot(snapshotId);
  }

  async getRegulatorySnapshot(snapshotId: string): Promise<RegulatorySnapshot> {
    const result = await prisma.$queryRaw`
      SELECT 
        id,
        business_account_id as "businessAccountId",
        snapshot_name as "snapshotName",
        snapshot_description as "snapshotDescription",
        snapshot_date as "snapshotDate",
        snapshot_type as "snapshotType",
        jurisdiction_code as "jurisdictionCode",
        snapshot_data as "snapshotData",
        includes_kpis as "includesKpis",
        includes_reports as "includesReports",
        includes_alerts as "includesAlerts",
        includes_thresholds as "includesThresholds",
        is_read_only as "isReadOnly",
        is_immutable as "isImmutable",
        retention_period_days as "retentionPeriodDays",
        access_count as "accessCount",
        last_accessed as "lastAccessed",
        created_by as "createdBy",
        created_at as "createdAt"
      FROM regulatory_snapshots
      WHERE id = ${snapshotId}::uuid
    `;
    
    return (result as any)[0];
  }

  async getRegulatorySnapshots(businessAccountId: string, filters: {
    snapshotType?: string;
    jurisdictionCode?: string;
    limit?: number;
  } = {}): Promise<RegulatorySnapshot[]> {
    const { snapshotType, jurisdictionCode, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        snapshot_name as "snapshotName",
        snapshot_description as "snapshotDescription",
        snapshot_date as "snapshotDate",
        snapshot_type as "snapshotType",
        jurisdiction_code as "jurisdictionCode",
        snapshot_data as "snapshotData",
        includes_kpis as "includesKpis",
        includes_reports as "includesReports",
        includes_alerts as "includesAlerts",
        includes_thresholds as "includesThresholds",
        is_read_only as "isReadOnly",
        is_immutable as "isImmutable",
        retention_period_days as "retentionPeriodDays",
        access_count as "accessCount",
        last_accessed as "lastAccessed",
        created_by as "createdBy",
        created_at as "createdAt"
      FROM regulatory_snapshots
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (snapshotType) {
      query += ` AND snapshot_type = '${snapshotType}'`;
    }
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    query += ` ORDER BY snapshot_date DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as RegulatorySnapshot[];
  }

  // Helper Methods
  private calculatePerformanceRating(currentValue: number, targetValue?: number): string {
    if (!targetValue) return 'average';
    
    const variance = Math.abs((currentValue - targetValue) / targetValue) * 100;
    
    if (variance <= 5) return 'excellent';
    if (variance <= 10) return 'good';
    if (variance <= 20) return 'average';
    if (variance <= 30) return 'poor';
    return 'critical';
  }

  private async calculateTrendDirection(
    businessAccountId: string,
    kpiName: string,
    currentValue: number
  ): Promise<string> {
    // Get previous KPI values to determine trend
    const previousKpis = await this.getRegulatoryKPIs(businessAccountId, {
      limit: 5
    });
    
    if (previousKpis.length < 2) return 'stable';
    
    const recentValues = previousKpis
      .filter(kpi => kpi.kpiName === kpiName)
      .slice(0, 3)
      .map(kpi => kpi.kpiValue);
    
    if (recentValues.length < 2) return 'stable';
    
    const trend = recentValues[recentValues.length - 1] - recentValues[0];
    const threshold = Math.abs(currentValue) * 0.05; // 5% threshold
    
    if (trend > threshold) return 'up';
    if (trend < -threshold) return 'down';
    return 'stable';
  }

  private async gatherSnapshotData(
    businessAccountId: string,
    jurisdictionCode: string,
    options: {
      includesKpis: boolean;
      includesReports: boolean;
      includesAlerts: boolean;
      includesThresholds: boolean;
    }
  ): Promise<any> {
    const snapshotData: any = {
      timestamp: new Date().toISOString(),
      businessAccountId,
      jurisdictionCode
    };
    
    if (options.includesKpis) {
      snapshotData.kpis = await this.getRegulatoryKPIs(businessAccountId, {
        jurisdictionCode,
        limit: 100
      });
    }
    
    if (options.includesReports) {
      snapshotData.reports = await this.getRegulatoryReports(businessAccountId, {
        jurisdictionCode,
        limit: 100
      });
    }
    
    if (options.includesAlerts) {
      snapshotData.alerts = await this.getRegulatoryAlerts(businessAccountId, {
        jurisdictionCode,
        limit: 100
      });
    }
    
    if (options.includesThresholds) {
      snapshotData.thresholds = await this.getComplianceThresholds(businessAccountId, {
        jurisdictionCode,
        limit: 100
      });
    }
    
    return snapshotData;
  }

  async getRegulatoryAlerts(businessAccountId: string, filters: {
    jurisdictionCode?: string;
    alertType?: string;
    severity?: string;
    status?: string;
    limit?: number;
  } = {}): Promise<RegulatoryAlert[]> {
    const { jurisdictionCode, alertType, severity, status, limit = 50 } = filters;
    
    let query = `
      SELECT 
        id,
        business_account_id as "businessAccountId",
        alert_type as "alertType",
        severity,
        title,
        description,
        jurisdiction_code as "jurisdictionCode",
        threshold_id as "thresholdId",
        metric_name as "metricName",
        current_value as "currentValue",
        threshold_value as "thresholdValue",
        variance_amount as "varianceAmount",
        variance_percentage as "variancePercentage",
        alert_data as "alertData",
        status,
        acknowledged_by as "acknowledgedBy",
        acknowledged_at as "acknowledgedAt",
        resolution_notes as "resolutionNotes",
        resolved_by as "resolvedBy",
        resolved_at as "resolvedAt",
        auto_generated as "autoGenerated",
        notification_sent as "notificationSent",
        regulatory_notification_required as "regulatoryNotificationRequired",
        regulatory_notification_sent as "regulatoryNotificationSent",
        created_at as "createdAt",
        updated_at as "updatedAt"
      FROM regulatory_alerts
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    if (jurisdictionCode) {
      query += ` AND jurisdiction_code = '${jurisdictionCode}'`;
    }
    
    if (alertType) {
      query += ` AND alert_type = '${alertType}'`;
    }
    
    if (severity) {
      query += ` AND severity = '${severity}'`;
    }
    
    if (status) {
      query += ` AND status = '${status}'`;
    }
    
    query += ` ORDER BY created_at DESC LIMIT ${limit}`;
    
    const result = await prisma.$queryRawUnsafe(query);
    return result as RegulatoryAlert[];
  }

  // Analytics and Dashboard Methods
  async getRegulatoryDashboard(businessAccountId: string, language: 'en' | 'ar' = 'en'): Promise<any> {
    const complianceSummary = await this.getComplianceSummary(businessAccountId);
    const kpiSummary = await this.getKPISummary(businessAccountId);
    const reportingStatus = await this.getReportingStatus(businessAccountId);
    const recentAlerts = await this.getRegulatoryAlerts(businessAccountId, { limit: 10 });
    
    return {
      summary: language === 'ar' ? {
        dashboardTitle: 'لوحة معلومات التنظيم والرقابة',
        totalAlerts: complianceSummary.totalAlerts,
        criticalAlerts: complianceSummary.criticalAlerts,
        compliantMetrics: complianceSummary.compliantMetrics,
        nonCompliantMetrics: complianceSummary.nonCompliantMetrics,
        totalKPIs: kpiSummary.totalKPIs,
        realTimeKPIs: kpiSummary.realTimeKPIs,
        pendingReports: reportingStatus.reportsDueSoon,
        generatedAt: new Date().toISOString()
      } : {
        dashboardTitle: 'Regulatory Dashboard',
        totalAlerts: complianceSummary.totalAlerts,
        criticalAlerts: complianceSummary.criticalAlerts,
        compliantMetrics: complianceSummary.compliantMetrics,
        nonCompliantMetrics: complianceSummary.nonCompliantMetrics,
        totalKPIs: kpiSummary.totalKPIs,
        realTimeKPIs: kpiSummary.realTimeKPIs,
        pendingReports: reportingStatus.reportsDueSoon,
        generatedAt: new Date().toISOString()
      },
      complianceSummary,
      kpiSummary,
      reportingStatus,
      recentAlerts,
      recommendations: this.generateRegulatoryRecommendations(
        complianceSummary,
        kpiSummary,
        reportingStatus,
        language
      )
    };
  }

  private async getComplianceSummary(businessAccountId: string): Promise<any> {
    const result = await prisma.$queryRaw`
      SELECT * FROM regulatory_compliance_summary
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    return (result as any)[0] || {
      totalAlerts: 0,
      criticalAlerts: 0,
      highAlerts: 0,
      activeAlerts: 0,
      regulatoryNotifications: 0,
      compliantMetrics: 0,
      nonCompliantMetrics: 0
    };
  }

  private async getKPISummary(businessAccountId: string): Promise<any> {
    const result = await prisma.$queryRaw`
      SELECT * FROM regulatory_kpi_summary
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    return (result as any)[0] || {
      totalKPIs: 0,
      realTimeKPIs: 0,
      excellentKPIs: 0,
      goodKPIs: 0,
      averageKPIs: 0,
      poorKPIs: 0,
      criticalKPIs: 0
    };
  }

  private async getReportingStatus(businessAccountId: string): Promise<any> {
    const result = await prisma.$queryRaw`
      SELECT * FROM regulatory_reporting_status
      WHERE business_account_id = ${businessAccountId}::uuid
    `;
    
    return (result as any)[0] || {
      totalReports: 0,
      submittedReports: 0,
      approvedReports: 0,
      rejectedReports: 0,
      reportsDueSoon: 0
    };
  }

  private generateRegulatoryRecommendations(
    complianceSummary: any,
    kpiSummary: any,
    reportingStatus: any,
    language: 'en' | 'ar'
  ): string[] {
    const recommendations = [];
    
    if (complianceSummary.criticalAlerts > 0) {
      recommendations.push(language === 'ar' ? 
        'تنبيهات حريرة تتطلب اهتمام فوري - راجع العتبات المنتهكة' : 
        'Critical alerts require immediate attention - review breached thresholds'
      );
    }
    
    if (complianceSummary.nonCompliantMetrics > 0) {
      recommendations.push(language === 'ar' ? 
        'مقاييس غير متوافقة - اتخذ إجراءات تصحيحية' : 
        'Non-compliant metrics detected - take corrective actions'
      );
    }
    
    if (reportingStatus.reportsDueSoon > 0) {
      recommendations.push(language === 'ar' ? 
        'تقارير مستحقة قريباً - أكمل التقارير المطلوبة' : 
        'Reports due soon - complete required submissions'
      );
    }
    
    if (kpiSummary.criticalKPIs > 0) {
      recommendations.push(language === 'ar' ? 
        'مؤشرات أداء حريرة - راجع استراتيجيات الأداء' : 
        'Critical KPIs - review performance strategies'
      );
    }
    
    return recommendations;
  }
}
