import { CmsPageResponse } from './cmsService';

export const HERO_SLIDES = [
  {
    title: 'homepage.hero.slide1.title',
    subtitle: 'homepage.hero.slide1.subtitle',
    ctaText: 'homepage.hero.slide1.cta',
    ctaLink: '/search',
    bgColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textColor: 'white',
  },
  {
    title: 'homepage.hero.slide2.title',
    subtitle: 'homepage.hero.slide2.subtitle',
    ctaText: 'homepage.hero.slide2.cta',
    ctaLink: '#paste-link',
    bgColor: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    textColor: 'white',
  },
  {
    title: 'homepage.hero.slide3.title',
    subtitle: 'homepage.hero.slide3.subtitle',
    ctaText: 'homepage.hero.slide3.cta',
    ctaLink: '#traveler',
    bgColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    textColor: 'white',
  },
  {
    title: 'homepage.hero.slide4.title',
    subtitle: 'homepage.hero.slide4.subtitle',
    ctaText: 'homepage.hero.slide4.cta',
    ctaLink: '/deals',
    bgColor: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    textColor: 'white',
  },
];

export const DEALS_PRODUCTS = [
  {
    id: 'deal-1',
    title: 'Apple iPhone 15 Pro Max 256GB',
    price: 949.99,
    originalPrice: 1099.99,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=300',
    shipping: 'payment.shipping.free',
    condition: 'New',
    sellerRating: 4.9,
    sellerReviews: 15234,
    discount: 14,
  },
  {
    id: 'deal-2',
    title: 'Sony PlayStation 5 Disc Edition',
    price: 449.99,
    originalPrice: 499.99,
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=300',
    shipping: 'payment.shipping.free',
    condition: 'New',
    sellerRating: 4.8,
    sellerReviews: 8921,
    discount: 10,
  },
  {
    id: 'deal-3',
    title: 'Samsung 65" 4K OLED Smart TV',
    price: 1497.99,
    originalPrice: 1997.99,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=300',
    shipping: 'payment.shipping.free',
    condition: 'New',
    sellerRating: 4.7,
    sellerReviews: 3456,
    discount: 25,
  },
  {
    id: 'deal-4',
    title: 'Apple MacBook Pro 14" M3 Pro',
    price: 1649.00,
    originalPrice: 1799.00,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300',
    shipping: 'payment.shipping.free',
    condition: 'New',
    sellerRating: 5.0,
    sellerReviews: 2341,
    discount: 8,
  },
  {
    id: 'deal-5',
    title: 'Dyson V15 Detect Cordless Vacuum',
    price: 549.99,
    originalPrice: 649.99,
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=300',
    shipping: 'payment.shipping.free',
    condition: 'Refurbished',
    sellerRating: 4.6,
    sellerReviews: 4521,
    discount: 15,
  },
];

export const CATEGORIES = [
  { id: '1', name: 'homepage.categories.items.electronics', slug: 'electronics', icon: 'smartphone', color: 'from-blue-500 to-blue-600' },
  { id: '2', name: 'homepage.categories.items.fashion', slug: 'fashion', icon: 'shirt', color: 'from-pink-500 to-pink-600' },
  { id: '3', name: 'homepage.categories.items.homeGarden', slug: 'home-garden', icon: 'home', color: 'from-green-500 to-green-600' },
  { id: '4', name: 'homepage.categories.items.sports', slug: 'sports', icon: 'activity', color: 'from-orange-500 to-orange-600' },
  { id: '5', name: 'homepage.categories.items.collectibles', slug: 'collectibles', icon: 'star', color: 'from-purple-500 to-purple-600' },
  { id: '6', name: 'homepage.categories.items.travelRequests', slug: 'travel-requests', icon: 'globe', color: 'from-cyan-500 to-cyan-600' },
];

export const CORE_VALUES = [
  { id: '1', title: 'homepage.values.items.travelEarn.title', description: 'homepage.values.items.travelEarn.desc', icon: 'globe', color: 'bg-blue-50 text-brand-blue' },
  { id: '2', title: 'homepage.values.items.pasteLink.title', description: 'homepage.values.items.pasteLink.desc', icon: 'link', color: 'bg-purple-50 text-purple-600' },
  { id: '3', title: 'homepage.values.items.auctions.title', description: 'homepage.values.items.auctions.desc', icon: 'dollar', color: 'bg-green-50 text-green-600' },
  { id: '4', title: 'homepage.values.items.protection.title', description: 'homepage.values.items.protection.desc', icon: 'shield', color: 'bg-orange-50 text-orange-600' },
];

export const FALLBACK_HOMEPAGE_DATA: CmsPageResponse = {
  page: {
    id: 'fallback-page',
    slug: 'homepage',
    title: 'Home',
    description: 'Welcome to MNbarh',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  sections: [
    {
      id: 'fallback-carousel',
      pageId: 'fallback-page',
      type: 'carousel',
      title: 'Hero Banner',
      enabled: true,
      sortOrder: 0,
      config: {},
      items: HERO_SLIDES.map((slide, i) => ({
        id: `slide-${i}`,
        sectionId: 'fallback-carousel',
        sortOrder: i,
        data: slide,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'fallback-deals',
      pageId: 'fallback-page',
      type: 'deals',
      title: "homepage.deals.title",
      enabled: true,
      sortOrder: 1,
      config: {},
      items: DEALS_PRODUCTS.map((prod, i) => ({
        id: `prod-${i}`,
        sectionId: 'fallback-deals',
        sortOrder: i,
        data: prod,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'fallback-categories',
      pageId: 'fallback-page',
      type: 'categories',
      title: 'homepage.categories.title',
      enabled: true,
      sortOrder: 2,
      config: {},
      items: CATEGORIES.map((cat, i) => ({
        id: `cat-${i}`,
        sectionId: 'fallback-categories',
        sortOrder: i,
        data: cat,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'fallback-values',
      pageId: 'fallback-page',
      type: 'values',
      title: 'homepage.values.title',
      enabled: true,
      sortOrder: 3,
      config: {},
      items: CORE_VALUES.map((val, i) => ({
        id: `val-${i}`,
        sectionId: 'fallback-values',
        sortOrder: i,
        data: val,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      })),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
