import { useState, useEffect } from 'react';
import { Card, Button, Input, Steps, Typography, Alert, Space, message, List } from 'antd';
import { SafetyCertificateOutlined, MobileOutlined, CheckCircleOutlined } from '@ant-design/icons';
import axios from 'axios';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';

const { Title, Text, Paragraph } = Typography;
const { Step } = Steps;

const MFASetup = () => {
  const [currentStep, setCurrentStep] = useState(0);
  const [secret, setSecret] = useState('');
  const [qrCodeUrl, setQrCodeUrl] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const { token } = useAuth();
  const navigate = useNavigate();

  const fetchSecret = async () => {
    try {
      setLoading(true);
      const response = await axios.post(
        `${import.meta.env.VITE_API_URL}/auth/mfa/setup`,
        {},
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setSecret(response.data.secret);
      setQrCodeUrl(response.data.qrCodeUrl);
      setLoading(false);
    } catch (error) {
      console.error('Failed to fetch MFA secret', error);
      message.error('Failed to initialize MFA setup');
      setLoading(false);
    }
  };

  useEffect(() => {
    if (currentStep === 0) {
      fetchSecret();
    }
  }, []);

  const verifyCode = async () => {
    try {
      setLoading(true);
      const response = await axios.post(
        `${import.meta.env.VITE_API_URL}/auth/mfa/verify`,
        { token: verificationCode },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      
      if (response.data.success) {
        setBackupCodes(response.data.backupCodes);
        setCurrentStep(2);
        message.success('MFA enabled successfully!');
      }
      setLoading(false);
    } catch (error) {
      console.error('Failed to verify code', error);
      message.error('Invalid code. Please try again.');
      setLoading(false);
    }
  };

  const handleFinish = () => {
    navigate('/dashboard');
  };

  return (
    <div style={{ maxWidth: 800, margin: '40px auto', padding: '0 20px' }}>
      <Card title={<Title level={3}><SafetyCertificateOutlined /> Two-Factor Authentication Setup</Title>}>
        <Steps current={currentStep} style={{ marginBottom: 40 }}>
          <Step title="Scan Code" icon={<MobileOutlined />} />
          <Step title="Verify" icon={<SafetyCertificateOutlined />} />
          <Step title="Backup Codes" icon={<CheckCircleOutlined />} />
        </Steps>

        {currentStep === 0 && (
          <div style={{ textAlign: 'center' }}>
            <Title level={4}>Scan this QR Code</Title>
            <Paragraph>
              Open your authenticator app (Google Authenticator, Authy, etc.) and scan the code below.
            </Paragraph>
            
            <div style={{ margin: '30px 0', display: 'flex', justifyContent: 'center' }}>
              {loading ? (
                <div style={{ height: 200, width: 200, background: '#f0f0f0', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>Loading...</div>
              ) : (
                <img src={qrCodeUrl} alt="MFA QR Code" style={{ width: 200, height: 200, border: '1px solid #eee' }} />
              )}
            </div>

            <Paragraph type="secondary">
              Can't scan the code? Enter this secret manually:
            </Paragraph>
            <Paragraph code copyable style={{ fontSize: 16 }}>
              {secret}
            </Paragraph>

            <Button type="primary" size="large" onClick={() => setCurrentStep(1)} style={{ marginTop: 20 }}>
              I've scanned the code
            </Button>
          </div>
        )}

        {currentStep === 1 && (
          <div style={{ textAlign: 'center', maxWidth: 400, margin: '0 auto' }}>
            <Title level={4}>Enter Verification Code</Title>
            <Paragraph>
              Enter the 6-digit code generated by your authenticator app to verify setup.
            </Paragraph>

            <Input.OTP 
              length={6} 
              value={verificationCode} 
              onChange={setVerificationCode} 
              size="large" 
              style={{ marginBottom: 20 }} 
            />

            <div style={{ marginTop: 20 }}>
              <Space>
                <Button onClick={() => setCurrentStep(0)}>Back</Button>
                <Button 
                  type="primary" 
                  onClick={verifyCode} 
                  loading={loading} 
                  disabled={verificationCode.length !== 6}
                >
                  Verify & Enable
                </Button>
              </Space>
            </div>
          </div>
        )}

        {currentStep === 2 && (
          <div style={{ textAlign: 'center' }}>
            <Alert
              message="MFA Enabled Successfully"
              description="Your account is now secured with two-factor authentication."
              type="success"
              showIcon
              style={{ marginBottom: 24, textAlign: 'left' }}
            />

            <Title level={4} type="danger">Save Your Backup Codes</Title>
            <Paragraph>
              If you lose access to your authenticator device, you can use these codes to log in. 
              <Text strong> Each code can only be used once.</Text>
            </Paragraph>

            <div style={{ background: '#f5f5f5', padding: 20, borderRadius: 8, marginBottom: 24 }}>
              <List
                grid={{ gutter: 16, column: 2 }}
                dataSource={backupCodes}
                renderItem={(item: string) => (
                  <List.Item>
                    <Text code style={{ fontSize: 16 }}>{item}</Text>
                  </List.Item>
                )}
              />
            </div>

            <Button type="primary" size="large" onClick={handleFinish}>
              Done
            </Button>
          </div>
        )}
      </Card>
    </div>
  );
};

export default MFASetup;
