/**
 * Global Event Logging System - Strict Event Taxonomy
 * SECURITY: All events must be validated and logged via backend API
 * Frontend logging is informational only - backend enforces security
 */

// Event Categories - High-level grouping of events
export enum EventCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  PAYMENT = 'PAYMENT',
  AUCTION = 'AUCTION',
  WALLET = 'WALLET',
  ESCROW = 'ESCROW',
  DISPUTE = 'DISPUTE',
  PAYOUT = 'PAYOUT',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  SYSTEM = 'SYSTEM',
  SECURITY = 'SECURITY',
  API = 'API'
}

// Event Types - Specific actions within categories
export enum EventType {
  // Authentication Events
  LOGIN_ATTEMPT = 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',

  // Authorization Events
  PERMISSION_CHECK = 'PERMISSION_CHECK',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',

  // Payment Events
  PAYMENT_INTENT_CREATED = 'PAYMENT_INTENT_CREATED',
  PAYMENT_INTENT_CONFIRMED = 'PAYMENT_INTENT_CONFIRMED',
  PAYMENT_INTENT_FAILED = 'PAYMENT_INTENT_FAILED',
  PAYMENT_INTENT_CANCELLED = 'PAYMENT_INTENT_CANCELLED',
  PAYMENT_STATUS_CHECK = 'PAYMENT_STATUS_CHECK',
  PAYMENT_REFUND_REQUESTED = 'PAYMENT_REFUND_REQUESTED',
  PAYMENT_REFUND_PROCESSED = 'PAYMENT_REFUND_PROCESSED',

  // Auction Events
  AUCTION_CREATED = 'AUCTION_CREATED',
  AUCTION_UPDATED = 'AUCTION_UPDATED',
  AUCTION_CANCELLED = 'AUCTION_CANCELLED',
  AUCTION_COMPLETED = 'AUCTION_COMPLETED',
  BID_PLACED = 'BID_PLACED',
  BID_CANCELLED = 'BID_CANCELLED',
  BID_ACCEPTED = 'BID_ACCEPTED',
  BID_REJECTED = 'BID_REJECTED',

  // Wallet Events
  WALLET_CREATED = 'WALLET_CREATED',
  WALLET_BALANCE_CHECK = 'WALLET_BALANCE_CHECK',
  WALLET_DEPOSIT = 'WALLET_DEPOSIT',
  WALLET_WITHDRAWAL = 'WALLET_WITHDRAWAL',
  WALLET_FROZEN = 'WALLET_FROZEN',
  WALLET_UNFROZEN = 'WALLET_UNFROZEN',

  // Escrow Events
  ESCROW_CREATED = 'ESCROW_CREATED',
  ESCROW_FUNDED = 'ESCROW_FUNDED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  ESCROW_CANCELLED = 'ESCROW_CANCELLED',
  ESCROW_DISPUTED = 'ESCROW_DISPUTED',

  // Dispute Events
  DISPUTE_CREATED = 'DISPUTE_CREATED',
  DISPUTE_UPDATED = 'DISPUTE_UPDATED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_ESCALATED = 'DISPUTE_ESCALATED',
  EVIDENCE_SUBMITTED = 'EVIDENCE_SUBMITTED',

  // Payout Events
  PAYOUT_REQUESTED = 'PAYOUT_REQUESTED',
  PAYOUT_PROCESSED = 'PAYOUT_PROCESSED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  PAYOUT_CANCELLED = 'PAYOUT_CANCELLED',

  // User Management Events
  USER_REGISTERED = 'USER_REGISTERED',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_VERIFIED = 'USER_VERIFIED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_UNSUSPENDED = 'USER_UNSUSPENDED',
  USER_DELETED = 'USER_DELETED',

  // System Events
  SYSTEM_STARTUP = 'SYSTEM_STARTUP',
  SYSTEM_SHUTDOWN = 'SYSTEM_SHUTDOWN',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  BACKUP_CREATED = 'BACKUP_CREATED',
  BACKUP_RESTORED = 'BACKUP_RESTORED',

  // Security Events
  SECURITY_ALERT = 'SECURITY_ALERT',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_ACCESS_ATTEMPT = 'INVALID_ACCESS_ATTEMPT',
  DATA_BREACH_ATTEMPT = 'DATA_BREACH_ATTEMPT',

  // API Events
  API_REQUEST = 'API_REQUEST',
  API_RESPONSE = 'API_RESPONSE',
  API_ERROR = 'API_ERROR',
  API_TIMEOUT = 'API_TIMEOUT'
}

// Actor Types - Who performed the action
export enum ActorType {
  USER = 'USER',
  ADMIN = 'ADMIN',
  OPS = 'OPS',
  SYSTEM = 'SYSTEM'
}

// Target Types - What was affected by the action
export enum TargetType {
  AUCTION = 'AUCTION',
  WALLET = 'WALLET',
  ESCROW = 'ESCROW',
  DISPUTE = 'DISPUTE',
  PAYOUT = 'PAYOUT',
  USER = 'USER',
  PAYMENT = 'PAYMENT',
  SYSTEM = 'SYSTEM',
  API = 'API'
}

// Event Severity Levels
export enum EventSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

// Event Status
export enum EventStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT'
}

// Core Event Interface
export interface SecurityEvent {
  id?: string; // Generated by backend
  timestamp?: string; // Generated by backend
  
  // Required fields - strict taxonomy
  event_category: EventCategory;
  event_type: EventType;
  actor_type: ActorType;
  actor_id: string | null; // null for SYSTEM events
  target_type: TargetType;
  target_id?: string; // Optional: ID of the affected entity
  
  // Event details
  severity: EventSeverity;
  status: EventStatus;
  
  // Context information
  ip_address?: string; // Will be captured by backend
  user_agent?: string; // Will be captured by backend
  session_id?: string;
  request_id?: string;
  
  // Additional data (validated by backend)
  metadata?: Record<string, any>; // Flexible metadata object
  
  // Security fields
  security_level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  risk_score?: number; // Calculated by backend (0-100)
  
  // Frontend tracking
  frontend_timestamp: number; // Client-side timestamp
  frontend_session_id: string; // Client session tracking
}

// Event Creation Interface (what frontend sends)
export interface CreateSecurityEventRequest {
  event_category: EventCategory;
  event_type: EventType;
  actor_type: ActorType;
  actor_id: string | null;
  target_type: TargetType;
  target_id?: string;
  severity: EventSeverity;
  status: EventStatus;
  metadata?: Record<string, any>;
  security_level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  frontend_timestamp: number;
  frontend_session_id: string;
}

// Event Response Interface
export interface SecurityEventResponse {
  success: boolean;
  event?: SecurityEvent;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
}

// Event Query Interface
export interface EventQueryParams {
  event_category?: EventCategory;
  event_type?: EventType;
  actor_type?: ActorType;
  actor_id?: string;
  target_type?: TargetType;
  target_id?: string;
  severity?: EventSeverity;
  status?: EventStatus;
  date_from?: string;
  date_to?: string;
  limit?: number;
  offset?: number;
}

// Event Statistics
export interface EventStatistics {
  total_events: number;
  events_by_category: Record<EventCategory, number>;
  events_by_severity: Record<EventSeverity, number>;
  events_by_actor_type: Record<ActorType, number>;
  recent_critical_events: SecurityEvent[];
  security_alerts: number;
}

// Event Validation Rules
export interface EventValidationRule {
  category: EventCategory;
  allowed_types: EventType[];
  required_actor_types: ActorType[];
  required_target_types: TargetType[];
  max_metadata_size: number; // Maximum metadata object size in bytes
  required_fields: string[];
}

// Audit Log Entry
export interface AuditLogEntry {
  id: string;
  timestamp: string;
  event: SecurityEvent;
  changes?: {
    field: string;
    old_value: any;
    new_value: any;
  }[];
  compliance_flags?: string[];
}

// Security Alert Interface
export interface SecurityAlert {
  id: string;
  timestamp: string;
  event_id: string;
  alert_type: 'SUSPICIOUS_ACTIVITY' | 'RATE_LIMIT_EXCEEDED' | 'INVALID_ACCESS' | 'DATA_BREACH_ATTEMPT';
  severity: EventSeverity;
  description: string;
  actor_info?: {
    type: ActorType;
    id: string;
    email?: string;
  };
  target_info?: {
    type: TargetType;
    id: string;
  };
  recommended_actions: string[];
  acknowledged: boolean;
  acknowledged_by?: string;
  acknowledged_at?: string;
}