@echo off
echo Running migrations inside Docker containers...

echo [1/7] Migrating Auth Service...
docker-compose run --rm auth-service npx prisma migrate dev --name init

echo [2/7] Migrating Listing Service...
docker-compose run --rm listing-service npx prisma migrate dev --name init

echo [3/7] Migrating Auction Service...
docker-compose run --rm auction-service npx prisma migrate dev --name init

echo [4/7] Migrating Payment Service...
docker-compose run --rm payment-service npx prisma migrate dev --name init

echo [5/7] Migrating Crowdship Service...
docker-compose run --rm crowdship-service npx prisma migrate dev --name init

echo [6/7] Migrating Recommendation Service...
docker-compose run --rm recommendation-service npx prisma migrate dev --name init

echo [7/7] Migrating Rewards Service...
docker-compose run --rm rewards-service npx prisma migrate dev --name init

echo All migrations completed!
