apiVersion: v1
kind: Service
metadata:
  name: { .Release.Name }-recommendation-service
spec:
  type: { .Values.service.type }
  selector:
    app: recommendation-service
  ports:
    - port: { .Values.service.port }
      targetPort: 3000
