# PCI-DSS Security Logging and Monitoring Configuration
# Requirements: 19.1 - Set up security logging and monitoring
---
# Namespace for security logging
apiVersion: v1
kind: Namespace
metadata:
  name: security-logging
  labels:
    app.kubernetes.io/name: security-logging
    security.mnbara.com/pci-dss: "true"

---
# Fluentd ConfigMap for PCI-DSS compliant logging
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-pci-config
  namespace: security-logging
  labels:
    app.kubernetes.io/name: fluentd
    security.mnbara.com/pci-dss: "true"
data:
  fluent.conf: |
    # PCI-DSS Compliant Logging Configuration
    # Requirement 10: Track and monitor all access
    
    <source>
      @type tail
      path /var/log/containers/*payment*.log
      pos_file /var/log/fluentd-payment.pos
      tag payment.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    
    <source>
      @type tail
      path /var/log/containers/*auth*.log
      pos_file /var/log/fluentd-auth.pos
      tag auth.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    
    # Mask sensitive data before forwarding
    <filter payment.**>
      @type record_transformer
      enable_ruby true
      <record>
        message ${record["message"].gsub(/\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13})\b/, '****-****-****-****')}
        masked true
      </record>
    </filter>
    
    # Add PCI-DSS required fields
    <filter **>
      @type record_transformer
      <record>
        cluster ${ENV['CLUSTER_NAME']}
        environment ${ENV['ENVIRONMENT']}
        pci_compliant true
        log_timestamp ${time.strftime('%Y-%m-%dT%H:%M:%S.%LZ')}
      </record>
    </filter>
    
    # Forward to Elasticsearch with encryption
    <match **>
      @type elasticsearch
      host elasticsearch-logs.elk.svc.cluster.local
      port 9200
      scheme https
      ssl_verify true
      ca_file /etc/fluentd/certs/ca.crt
      client_cert /etc/fluentd/certs/client.crt
      client_key /etc/fluentd/certs/client.key
      logstash_format true
      logstash_prefix pci-logs
      include_timestamp true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/pci
        flush_mode interval
        flush_interval 5s
        retry_type exponential_backoff
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>

---
# Audit logging configuration for payment service
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-logging-config
  namespace: payment-cde
  labels:
    app.kubernetes.io/name: payment-service
    security.mnbara.com/pci-dss: "true"
data:
  audit-config.json: |
    {
      "enabled": true,
      "level": "detailed",
      "events": {
        "authentication": {
          "log_success": true,
          "log_failure": true,
          "include_ip": true,
          "include_user_agent": true
        },
        "authorization": {
          "log_success": true,
          "log_failure": true,
          "include_resource": true,
          "include_action": true
        },
        "data_access": {
          "log_read": true,
          "log_write": true,
          "log_delete": true,
          "include_record_id": true
        },
        "payment": {
          "log_initiation": true,
          "log_completion": true,
          "log_failure": true,
          "log_refund": true,
          "include_amount": true,
          "mask_card_data": true
        },
        "admin": {
          "log_all": true,
          "include_changes": true
        }
      },
      "retention": {
        "days": 365,
        "archive_after_days": 90,
        "encryption": "AES-256-GCM"
      },
      "integrity": {
        "enabled": true,
        "algorithm": "SHA-256",
        "chain_logs": true
      }
    }

---
# Prometheus rules for security monitoring
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pci-dss-security-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    security.mnbara.com/pci-dss: "true"
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: pci-dss-security
      rules:
        # Authentication failures
        - alert: HighAuthenticationFailureRate
          expr: |
            sum(rate(auth_login_failures_total{service="payment-service"}[5m])) > 10
          for: 2m
          labels:
            severity: critical
            compliance: pci-dss
            requirement: "10.2.4"
          annotations:
            summary: "High authentication failure rate detected"
            description: "More than 10 authentication failures per second in payment service"
            runbook_url: "https://docs.mnbara.com/runbooks/auth-failures"
        
        # Unauthorized access attempts
        - alert: UnauthorizedAccessAttempt
          expr: |
            sum(rate(http_requests_total{service="payment-service",status=~"401|403"}[5m])) > 5
          for: 1m
          labels:
            severity: warning
            compliance: pci-dss
            requirement: "10.2.4"
          annotations:
            summary: "Unauthorized access attempts detected"
            description: "Multiple 401/403 responses from payment service"
        
        # Privilege escalation
        - alert: PrivilegeEscalationAttempt
          expr: |
            sum(rate(audit_privilege_escalation_attempts_total[5m])) > 0
          for: 0m
          labels:
            severity: critical
            compliance: pci-dss
            requirement: "10.2.5"
          annotations:
            summary: "Privilege escalation attempt detected"
            description: "Potential privilege escalation attempt in CDE"
        
        # Audit log tampering
        - alert: AuditLogIntegrityFailure
          expr: |
            audit_log_integrity_check_failures_total > 0
          for: 0m
          labels:
            severity: critical
            compliance: pci-dss
            requirement: "10.5"
          annotations:
            summary: "Audit log integrity check failed"
            description: "Potential tampering detected in audit logs"
        
        # Payment anomalies
        - alert: UnusualPaymentVolume
          expr: |
            sum(rate(payment_transactions_total[1h])) > 
            (sum(rate(payment_transactions_total[24h] offset 1d)) * 3)
          for: 15m
          labels:
            severity: warning
            compliance: pci-dss
            requirement: "10.6"
          annotations:
            summary: "Unusual payment volume detected"
            description: "Payment volume is 3x higher than normal"
        
        # Network segmentation breach
        - alert: CDENetworkSegmentationBreach
          expr: |
            sum(rate(network_policy_violations_total{namespace="payment-cde"}[5m])) > 0
          for: 0m
          labels:
            severity: critical
            compliance: pci-dss
            requirement: "1.3"
          annotations:
            summary: "CDE network segmentation breach detected"
            description: "Unauthorized network traffic detected in CDE"
        
        # Encryption failures
        - alert: EncryptionFailure
          expr: |
            sum(rate(encryption_operation_failures_total{service="payment-service"}[5m])) > 0
          for: 1m
          labels:
            severity: critical
            compliance: pci-dss
            requirement: "3.4"
          annotations:
            summary: "Encryption operation failed"
            description: "Encryption/decryption failure in payment service"

---
# Grafana dashboard for PCI-DSS monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-pci-dashboard
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    security.mnbara.com/pci-dss: "true"
    grafana_dashboard: "1"
data:
  pci-dss-dashboard.json: |
    {
      "dashboard": {
        "title": "PCI-DSS Security Monitoring",
        "uid": "pci-dss-security",
        "tags": ["pci-dss", "security", "compliance"],
        "timezone": "UTC",
        "panels": [
          {
            "title": "Authentication Events",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
            "targets": [
              {
                "expr": "sum(rate(auth_login_total{service=\"payment-service\"}[5m])) by (status)",
                "legendFormat": "{{status}}"
              }
            ]
          },
          {
            "title": "Payment Transactions",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
            "targets": [
              {
                "expr": "sum(rate(payment_transactions_total[5m])) by (status)",
                "legendFormat": "{{status}}"
              }
            ]
          },
          {
            "title": "Security Alerts",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 8},
            "targets": [
              {
                "expr": "count(ALERTS{compliance=\"pci-dss\",alertstate=\"firing\"})"
              }
            ]
          },
          {
            "title": "Network Policy Violations",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 6, "y": 8},
            "targets": [
              {
                "expr": "sum(increase(network_policy_violations_total{namespace=\"payment-cde\"}[24h]))"
              }
            ]
          },
          {
            "title": "Audit Log Volume",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 12},
            "targets": [
              {
                "expr": "sum(rate(audit_log_entries_total[5m])) by (event_type)",
                "legendFormat": "{{event_type}}"
              }
            ]
          },
          {
            "title": "Access Control Events",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 12},
            "targets": [
              {
                "expr": "sum(rate(authorization_decisions_total[5m])) by (decision)",
                "legendFormat": "{{decision}}"
              }
            ]
          }
        ]
      }
    }

---
# Kubernetes audit policy for CDE
apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  name: pci-dss-audit-policy
rules:
  # Log all requests to payment-cde namespace at RequestResponse level
  - level: RequestResponse
    namespaces: ["payment-cde"]
    verbs: ["create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["pods", "services", "secrets", "configmaps"]
      - group: "apps"
        resources: ["deployments", "statefulsets"]
  
  # Log all authentication events
  - level: Metadata
    users: ["system:anonymous"]
    verbs: ["get", "list", "watch"]
  
  # Log all secret access
  - level: Metadata
    resources:
      - group: ""
        resources: ["secrets"]
    namespaces: ["payment-cde"]
  
  # Log all RBAC changes
  - level: RequestResponse
    resources:
      - group: "rbac.authorization.k8s.io"
        resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
